package com.personalassistant.companion.keyguardtests;

import android.app.*;
import android.app.role.RoleManager;
import android.content.*;
import android.os.*;

/** Disposable-emulator-only secure-keyguard/foreground lifecycle check. No cloud calls. */
public final class KeyguardInstrumentation extends Instrumentation {
    private String mode,expectedDetector;
    @Override public void onCreate(Bundle args){super.onCreate(args);mode=args.getString("mode","start");expectedDetector=args.getString("expected_detector","");start();}
    @Override public void onStart(){Bundle result=new Bundle();try{
        if(!"ranchu".equals(Build.HARDWARE)&&!"goldfish".equals(Build.HARDWARE))throw new IllegalStateException("Disposable emulator required; do not run on a physical phone");
        Context target=getTargetContext();SharedPreferences prefs=target.getSharedPreferences("assistant",0);
        if(!prefs.getString("token","").isEmpty())throw new IllegalStateException("Unpaired emulator required");
        if("stop".equals(mode)){target.stopService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));prefs.edit().putBoolean("wake_enabled",prefs.getBoolean("keyguard_before_wake",false)).putBoolean("voice_preview",prefs.getBoolean("keyguard_before_preview",false)).remove("keyguard_before_wake").remove("keyguard_before_preview").commit();result.putString("stream","Mic stopped and emulator preferences restored");finish(0,result);return;}
        if("cold".equals(mode)){boolean oldWake=prefs.getBoolean("wake_enabled",false),oldPreview=prefs.getBoolean("voice_preview",false);try{prefs.edit().putBoolean("wake_enabled",false).putBoolean("voice_preview",true).putString("voice_status","Cold microphone test pending").commit();long started=SystemClock.elapsedRealtime();target.startForegroundService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));String status="";while(SystemClock.elapsedRealtime()-started<15000){status=prefs.getString("voice_status","");if(status.equals("Ready for voice")||status.startsWith("Voice stopped:")||status.startsWith("Microphone could not start:"))break;Thread.sleep(20);}if(!status.equals("Ready for voice")||!prefs.getString("wake_detector","").equals("Wake disabled"))throw new IllegalStateException("Cold button voice loaded a model or failed: "+status);result.putLong("cold_microphone_ready_ms",SystemClock.elapsedRealtime()-started);result.putBoolean("wake_runtime_skipped",true);result.putString("stream","Wake-off microphone readiness verified without neural runtime initialization");}finally{target.stopService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));prefs.edit().putBoolean("wake_enabled",oldWake).putBoolean("voice_preview",oldPreview).commit();}finish(0,result);return;}
        if("selection".equals(mode)){boolean oldWake=prefs.getBoolean("wake_enabled",false),oldPreview=prefs.getBoolean("voice_preview",false);try{prefs.edit().putBoolean("wake_enabled",true).putBoolean("voice_preview",true).putString("wake_detector","").putString("voice_status","Detector selection pending").commit();target.startForegroundService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));long end=SystemClock.elapsedRealtime()+15000;String status="";while(SystemClock.elapsedRealtime()<end){status=prefs.getString("voice_status","");if(status.startsWith("Listening locally")||status.startsWith("Voice stopped:")||status.startsWith("Microphone could not start:")||status.startsWith("Wake model not installed"))break;Thread.sleep(20);}String selected=prefs.getString("wake_detector","");if(expectedDetector.isEmpty()||!status.startsWith("Listening locally")||!selected.equals(expectedDetector))throw new IllegalStateException("Service selected wrong wake adapter: "+selected+"; "+status);result.putString("service_wake_detector",selected);result.putBoolean("actual_service_selected_packaged_model",true);result.putString("stream","Actual foreground service selected the packaged optional wake adapter; unpaired emulator, preview only.");}finally{target.stopService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));prefs.edit().putBoolean("wake_enabled",oldWake).putBoolean("voice_preview",oldPreview).commit();}finish(0,result);return;}
        KeyguardManager guard=target.getSystemService(KeyguardManager.class);
        result.putBoolean("secure",guard.isDeviceSecure());result.putBoolean("locked_before",guard.isDeviceLocked());result.putBoolean("keyguard_before",guard.isKeyguardLocked());
        if(!guard.isDeviceSecure()||!guard.isDeviceLocked())throw new IllegalStateException("Secure emulator keyguard must be locked before test");
        if(!target.getSystemService(RoleManager.class).isRoleHeld(RoleManager.ROLE_ASSISTANT))throw new IllegalStateException("Assistant role required");
        if("entry_direct".equals(mode)){
            boolean beforeWake=prefs.getBoolean("wake_enabled",false),beforePreview=prefs.getBoolean("voice_preview",false);
            ActivityMonitor monitor=addMonitor("com.personalassistant.companion.VoiceEntryActivity",null,false);
            try{prefs.edit().putBoolean("wake_enabled",false).putBoolean("voice_preview",true).remove("voice_keyguard_callback_elapsed").remove("voice_entry_created_elapsed").remove("voice_entry_talk_elapsed").remove("voice_mic_ready_ns").remove("voice_first_pcm_ns").remove("voice_capture_started_ns").putString("voice_status","Locked entry direct callback pending").commit();
                Class<?> service=Class.forName("com.personalassistant.companion.AssistantVoiceInteractionService",true,target.getClassLoader());Object instance=service.getConstructor().newInstance();java.lang.reflect.Method attach=ContextWrapper.class.getDeclaredMethod("attachBaseContext",Context.class);attach.setAccessible(true);attach.invoke(instance,target);
                runOnMainSync(()->{try{service.getMethod("onLaunchVoiceAssistFromKeyguard").invoke(instance);}catch(Exception e){throw new RuntimeException(e);}});
                Activity entry=monitor.waitForActivityWithTimeout(5000);if(entry==null)throw new IllegalStateException("Callback failed to start voice Activity");
                long end=SystemClock.elapsedRealtime()+5000;String status="";while(SystemClock.elapsedRealtime()<end){status=prefs.getString("voice_status","");if(status.startsWith("Listening to your command")&&entry.hasWindowFocus())break;Thread.sleep(20);}
                long callback=prefs.getLong("voice_keyguard_callback_elapsed",0),created=prefs.getLong("voice_entry_created_elapsed",0),talk=prefs.getLong("voice_entry_talk_elapsed",0);
                if(!guard.isDeviceLocked()||!prefs.getBoolean("voice_entry_created_locked",false)||!entry.hasWindowFocus()||!status.startsWith("Listening to your command"))throw new IllegalStateException("Locked visible Activity microphone failed: "+status);
                result.putString("callback_invocation","Direct actual callback implementation under instrumentation; not a SystemUI affordance test");result.putBoolean("activity_visible_locked",true);result.putBoolean("device_remained_locked",guard.isDeviceLocked());result.putBoolean("screen_turned_on",target.getSystemService(PowerManager.class).isInteractive());result.putLong("callback_to_activity_ms",created-callback);result.putLong("callback_to_talk_request_ms",talk-callback);result.putLong("callback_to_observed_recording_ms",SystemClock.elapsedRealtime()-callback);long callbackNs=prefs.getLong("voice_keyguard_callback_ns",0),micNs=prefs.getLong("voice_mic_ready_ns",0),pcmNs=prefs.getLong("voice_first_pcm_ns",0),captureNs=prefs.getLong("voice_capture_started_ns",0);if(callbackNs<=0||micNs<callbackNs||pcmNs<micNs||captureNs<pcmNs)throw new IllegalStateException("Mic diagnostic clocks missing/out of order");result.putLong("callback_to_microphone_ready_ms",(micNs-callbackNs)/1000000);result.putLong("callback_to_first_pcm_ms",(pcmNs-callbackNs)/1000000);result.putLong("callback_to_capture_ms",(captureNs-callbackNs)/1000000);result.putString("wake_detector",prefs.getString("wake_detector",""));result.putString("microphone",status);runOnMainSync(entry::finish);result.putString("stream","Show-when-locked callback Activity, screen wake and visible mic readiness verified without unlock.");
            }finally{removeMonitor(monitor);target.stopService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));prefs.edit().putBoolean("wake_enabled",beforeWake).putBoolean("voice_preview",beforePreview).commit();}
            finish(0,result);return;
        }
        if("prepare_entry".equals(mode)){prefs.edit().putBoolean("keyguard_before_wake",prefs.getBoolean("keyguard_before_wake",prefs.getBoolean("wake_enabled",false))).putBoolean("keyguard_before_preview",prefs.getBoolean("keyguard_before_preview",prefs.getBoolean("voice_preview",false))).putBoolean("wake_enabled",false).putBoolean("voice_preview",true).remove("voice_keyguard_callback_elapsed").remove("voice_entry_created_elapsed").remove("voice_entry_talk_elapsed").putString("voice_status","Locked entry test pending").commit();result.putString("stream","Cold entry prepared; caller must send the system Voice Assist key outside instrumentation.");finish(0,result);return;}
        if("entry".equals(mode)){long end=SystemClock.elapsedRealtime()+5000;String status="";while(SystemClock.elapsedRealtime()<end){status=prefs.getString("voice_status","");if(status.startsWith("Listening to your command")||status.startsWith("Voice stopped:")||status.startsWith("Microphone could not start:"))break;Thread.sleep(20);}long callback=prefs.getLong("voice_keyguard_callback_elapsed",0),created=prefs.getLong("voice_entry_created_elapsed",0),talk=prefs.getLong("voice_entry_talk_elapsed",0);if(callback<=0||created<callback||talk<created||!prefs.getBoolean("voice_entry_created_locked",false)||!guard.isDeviceLocked()||!status.startsWith("Listening to your command"))throw new IllegalStateException("Locked system entry failed: "+status+" callback="+callback+" created="+created+" talk="+talk);result.putBoolean("actual_keyguard_callback",true);result.putBoolean("voice_only_activity_created_locked",true);result.putBoolean("device_remained_locked",guard.isDeviceLocked());result.putBoolean("screen_turned_on",target.getSystemService(PowerManager.class).isInteractive());result.putLong("callback_to_activity_ms",created-callback);result.putLong("callback_to_talk_request_ms",talk-callback);result.putString("microphone",status);result.putString("wake_detector",prefs.getString("wake_detector",""));result.putString("stream","System keyguard callback -> show-when-locked Activity -> Talk verified without unlocking.");finish(0,result);return;}
        if("probe".equals(mode)){result.putString("microphone",prefs.getString("voice_status",""));result.putBoolean("keyguard_session_launch_did_not_unlock",guard.isDeviceLocked());result.putString("stream","Secure keyguard and voice status snapshot after system Assist key launch");finish(0,result);return;}
        prefs.edit().putBoolean("keyguard_before_wake",prefs.getBoolean("keyguard_before_wake",prefs.getBoolean("wake_enabled",false))).putBoolean("keyguard_before_preview",prefs.getBoolean("keyguard_before_preview",prefs.getBoolean("voice_preview",false))).putBoolean("wake_enabled",true).putBoolean("voice_preview",true).commit();
        if("prepare".equals(mode)){result.putString("stream","Prepared unpaired emulator wake monitoring; caller must rebind assistant role outside instrumentation");finish(0,result);return;}
        target.startForegroundService(new Intent().setComponent(new ComponentName(target.getPackageName(),"com.personalassistant.companion.VoiceService")));
        String status="";long end=System.currentTimeMillis()+15000;while(System.currentTimeMillis()<end){status=prefs.getString("voice_status","");if(status.startsWith("Listening locally")||status.startsWith("Voice stopped:")||status.startsWith("Microphone could not start:")||status.startsWith("Wake model not installed"))break;Thread.sleep(200);}
        result.putString("microphone",status);result.putBoolean("locked_after",guard.isDeviceLocked());result.putBoolean("keyguard_after",guard.isKeyguardLocked());
        if(!status.startsWith("Listening locally"))throw new IllegalStateException("Background mic/wake did not start: "+status);
        if(!guard.isDeviceLocked())throw new IllegalStateException("Test unexpectedly unlocked the device");
        result.putString("stream","Foreground mic and local wake monitoring started while secure keyguard remained locked; virtual microphone only.");finish(0,result);
    }catch(Throwable error){result.putString("stream",android.util.Log.getStackTraceString(error));finish(1,result);}}
}
