package com.personalassistant.companion;

import android.app.*;
import android.app.job.JobScheduler;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import android.view.*;
import android.view.accessibility.AccessibilityNodeInfo;
import android.widget.*;
import java.io.*;
import java.util.*;
import org.json.*;

/** Real Activity widgets/lifecycle; synthetic private prefs, no cloud/paid API. */
public final class UiInstrumentation extends Instrumentation {
    private MainActivity activity;private SharedPreferences prefs;private Map<String,?> before;private String theme;private boolean screensOnly,reducedMotion;private byte[] chatBefore;
    @Override public void onCreate(Bundle args){super.onCreate(args);theme=args.getString("theme","light");screensOnly=Boolean.parseBoolean(args.getString("screens_only","false"));reducedMotion=Boolean.parseBoolean(args.getString("reduced_motion","false"));start();}
    @Override public void onStart(){Bundle result=new Bundle();int outcome=0;Context target=getTargetContext();try{
        check("ranchu".equals(Build.HARDWARE)||"goldfish".equals(Build.HARDWARE),"Disposable emulator required");prefs=Cloud.prefs(target);check(prefs.getString("token","").isEmpty(),"Unpaired emulator required");before=prefs.getAll();File chatFile=new File(target.getFilesDir(),"voice-chat.json");if(chatFile.isFile())chatBefore=java.nio.file.Files.readAllBytes(chatFile.toPath());chatFile.delete();target.stopService(new Intent(target,VoiceService.class));
        prefs.edit().clear().putString("ui_theme",theme).putString("origin","").putBoolean("wake_enabled",false).putBoolean("voice_live",false).putLong("update_checked",System.currentTimeMillis()).putBoolean("notification_permission_requested",true).commit();
        activity=(MainActivity)startActivitySync(new Intent(target,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));idle();
        if(screensOnly){prefs.edit().putString("token","offline-ui-fixture").putString("snapshot","{\"items\":[{\"id\":\"one\",\"name\":\"Bananas\",\"quantity\":\"6\",\"complete\":0,\"version\":1},{\"id\":\"two\",\"name\":\"Sparkling water\",\"quantity\":\"2 bottles\",\"complete\":0,\"version\":1},{\"id\":\"three\",\"name\":\"Bread\",\"quantity\":\"1 loaf\",\"complete\":0,\"version\":1}],\"recipes\":[]}").apply();idle();snapshots(target);result.putBoolean("synthetic_screenshots_only",true);result.putString("theme",theme);result.putString("stream","Native visual capture with synthetic UI data; no functional suite or cloud calls.");}
        else{click("nav_settings");
        EditText server=(EditText)view("server_address"),code=(EditText)view("pairing_code");runOnMainSync(()->{server.setText("https://draft.invalid");code.setText("TEST-PAIR-CODE");server.requestFocus();server.setSelection(8,13);});
        prefs.edit().putString("voice_status","Synthetic asynchronous state").putString("snapshot","{\"items\":[],\"recipes\":[]}").apply();target.sendBroadcast(new Intent("com.personalassistant.companion.VOICE_STATE").setPackage(target.getPackageName()));target.sendBroadcast(new Intent("com.personalassistant.companion.GROCERY_STATE").setPackage(target.getPackageName()));idle();
        check(server==view("server_address")&&code==view("pairing_code"),"Async state reconstructed pairing inputs");check(server.getText().toString().equals("https://draft.invalid")&&code.getText().toString().equals("TEST-PAIR-CODE"),"Async pairing draft lost");check(server.hasFocus()&&server.getSelectionStart()==8&&server.getSelectionEnd()==13,"Async pairing focus/selection lost");
        runOnMainSync(()->server.setText("bad address"));click("pair");check(code.getText().toString().equals("TEST-PAIR-CODE")&&((Button)view("pair")).isEnabled(),"Rejected address lost code or stuck button");result.putBoolean("pairing_async_input_focus_selection_preserved",true);result.putBoolean("invalid_pairing_address_no_network",true);
        prefs.edit().putString("token","offline-ui-fixture").putString("origin","").putString("snapshot","{\"items\":[{\"id\":\"cached\",\"name\":\"Milk\",\"quantity\":\"\",\"complete\":0,\"version\":1}],\"recipes\":[]}").putString("outbox","[{\"id\":\"complete-fixture\",\"operation\":\"complete\",\"target\":\"cached\",\"version\":1,\"complete\":true},{\"id\":\"add-fixture\",\"operation\":\"add\",\"items\":[{\"name\":\"Bread\",\"quantity\":\"\"}]}]").apply();idle();click("nav_shopping");
        EditText input=(EditText)view("shopping_item");runOnMainSync(()->{input.setText("Sparkling water");input.requestFocus();input.setSelection(4);});target.sendBroadcast(new Intent("com.personalassistant.companion.GROCERY_STATE").setPackage(target.getPackageName()));idle();check(input.getText().toString().equals("Sparkling water")&&input.hasFocus()&&input.getSelectionStart()==4,"Grocery update lost typing/focus");String shopping=texts();check(shopping.contains("Bread")&&!shopping.contains("Milk"),"UI did not project pending changes");click("shopping_add");idle();check(input.getText().toString().isEmpty(),"Add draft not cleared after durable save");check(Cloud.queue(target).length()==3&&Cloud.pendingList(target).getJSONArray("items").length()==3,"Offline add not saved once");result.putBoolean("shopping_async_draft_preserved",true);result.putBoolean("shopping_cached_pending_projection_and_offline_add",true);
        JSONObject cached=Cloud.cached(target);cached.put("recipes",new JSONArray().put(new JSONObject().put("id","pasta-fixture").put("title","Quick pasta").put("ingredients",new JSONArray().put(new JSONObject().put("name","Pasta").put("quantity","500 g")).put(new JSONObject().put("name","Tomatoes").put("quantity","2")).put(new JSONObject().put("name","Oil").put("quantity","1 tbsp")))));prefs.edit().putString("snapshot",cached.toString()).apply();idle();choose("Recipes");choose("Quick pasta");choose("1 tbsp Oil");choose("Add selected to list");check(Cloud.queue(target).length()==4,"Recipe selected items not saved once");JSONArray ingredients=Cloud.queue(target).getJSONObject(3).getJSONArray("items");check(ingredients.length()==2&&ingredients.getJSONObject(0).getString("name").equals("Pasta")&&ingredients.getJSONObject(1).getString("name").equals("Tomatoes"),"Recipe added unselected/combined ingredients");choose("Close");result.putBoolean("native_recipe_selected_ingredients_saved_once",true);
        click("nav_voice");prefs.edit().putFloat("voice_level",.65f).putLong("voice_metrics_elapsed",SystemClock.elapsedRealtime()).putBoolean("voice_mic_active",true).putString("voice_user_text","Test user words").putString("voice_reply","Test response").apply();idle();AppUi.Meter meter=(AppUi.Meter)view("voice_level");check(Math.abs(meter.amplitude-.65f)<.001&&meter.active,"Microphone level did not bind");VoiceChat.user(target,"ui-chat-fixture","Test user words",1000);VoiceChat.assistant(target,"ui-chat-fixture","Test response",1001,"acknowledgement","");idle();check(texts().contains("Test user words")&&texts().contains("Test response")&&texts().contains("Queued"),"Chat user/ack bubbles missing");VoiceChat.assistant(target,"ui-chat-fixture","Revised response",1002,"answer","");idle();JSONArray chat=VoiceChat.history(target);check(chat.length()==2&&chat.getJSONObject(1).getString("text").equals("Revised response")&&chat.getJSONObject(1).getLong("time")==1001,"Streaming chat duplicated bubble or moved first timestamp");check(texts().contains("Revised response")&&!texts().contains("Test response"),"Chat revision did not update bubble");result.putBoolean("timestamped_chat_stable_upsert_role_and_order",true);prefs.edit().putFloat("voice_level",.2f).putLong("voice_metrics_elapsed",SystemClock.elapsedRealtime()).apply();idle();check(Math.abs(meter.amplitude-.2f)<.001,"Second meter level did not settle");if(reducedMotion){check(!android.animation.ValueAnimator.areAnimatorsEnabled(),"Reduced motion scale not disabled");check(meter.transition==null||!meter.transition.isRunning(),"Meter animates with reduced motion");for(View parent=meter;parent!=null;parent=parent.getParent() instanceof View?(View)parent.getParent():null)check(Math.abs(parent.getAlpha()-1)<.001,"Page left faded with reduced motion");result.putBoolean("reduced_motion_no_meter_or_page_animation",true);}prefs.edit().putFloat("voice_level",0f).putLong("voice_metrics_elapsed",SystemClock.elapsedRealtime()).apply();idle();check(meter.active&&meter.amplitude==0,"Quiet active input not zero baseline");prefs.edit().putBoolean("voice_mic_active",false).putFloat("voice_level",0f).apply();idle();check(!meter.active,"Mic level remained active after stop");result.putBoolean("meter_and_separate_transcript_reply_binding",true);result.putBoolean("two_level_meter_settled_and_quiet_baseline",true);
        snapshots(target);result.putBoolean("screenshots_use_synthetic_ui_data",true);
        click("nav_settings");click("wake_sensitivity");choose("Sensitive -");check(prefs.getString("wake_sensitivity","").equals("sensitive"),"Sensitive choice not persisted");click("wake_sensitivity");choose("Balanced -");check(prefs.getString("wake_sensitivity","").equals("balanced"),"Balanced choice not persisted");result.putBoolean("sensitivity_control_persisted",true);
        prefs.edit().putString("update_release","{\"version_code\":999,\"version_name\":\"fixture\"}").putString("update_status","Fixture update ready").apply();idle();check(view("install_update").getVisibility()==View.VISIBLE,"Downloaded update install hidden");prefs.edit().remove("update_release").apply();idle();check(view("install_update").getVisibility()==View.GONE,"Stale update install displayed");result.putBoolean("update_ready_visibility",true);
        check(target.checkSelfPermission("android.permission.RECORD_AUDIO")==PackageManager.PERMISSION_GRANTED,"Grant microphone on emulator before lifecycle QA");click("nav_voice");click("background_listening");awaitMic(true,15000);check(prefs.getBoolean("wake_enabled",false),"Background toggle did not enable wake");click("background_listening");awaitMic(false,5000);check(!prefs.getBoolean("wake_enabled",true),"Background toggle did not disable wake");
        int pending=VoiceOutbox.pending(target);click("test_wake");awaitMic(true,15000);check(prefs.getBoolean("voice_listening_test",false),"Local wake test not enabled");click("background_listening");check(prefs.getBoolean("ui_test_background_desired",false)&&prefs.getBoolean("voice_listening_test",false),"Test toggle changed action mode prematurely");click("background_listening");click("test_wake");awaitMic(false,5000);check(!prefs.getBoolean("voice_listening_test",true)&&!prefs.getBoolean("wake_enabled",true),"Finished test did not restore background off");check(VoiceOutbox.pending(target)==pending,"Wake UI test created a command");result.putBoolean("background_on_off_and_local_test_state",true);result.putBoolean("local_test_ui_no_voice_outbox",true);
        result.putString("theme",theme);result.putString("stream","Actual UI inputs, focus, cache, offline changes, microphone state and local-test controls passed; no cloud requests.");}
    }catch(Throwable error){try{android.graphics.Bitmap failure=getUiAutomation().takeScreenshot();File directory=new File(target.getExternalFilesDir(null),"ui-qa");directory.mkdirs();try(OutputStream output=new FileOutputStream(new File(directory,"failure.png"))){failure.compress(android.graphics.Bitmap.CompressFormat.PNG,100,output);}failure.recycle();AccessibilityNodeInfo window=getUiAutomation().getRootInActiveWindow();result.putString("active_window",window==null?"none":window.toString());}catch(Exception ignored){}result.putString("stream",android.util.Log.getStackTraceString(error));outcome=1;}finally{
        target.stopService(new Intent(target,VoiceService.class));if(activity!=null)runOnMainSync(()->activity.finish());JobScheduler jobs=target.getSystemService(JobScheduler.class);for(int id:new int[]{210,211,212,216,218,219})jobs.cancel(id);if(before!=null)restore();try{File chatFile=new File(target.getFilesDir(),"voice-chat.json");if(chatBefore==null)chatFile.delete();else java.nio.file.Files.write(chatFile.toPath(),chatBefore);}catch(Exception ignored){}
    }finish(outcome,result);}
    private void restore(){SharedPreferences.Editor edit=prefs.edit().clear();for(Map.Entry<String,?> entry:before.entrySet()){Object value=entry.getValue();String key=entry.getKey();if(value instanceof String)edit.putString(key,(String)value);else if(value instanceof Boolean)edit.putBoolean(key,(Boolean)value);else if(value instanceof Integer)edit.putInt(key,(Integer)value);else if(value instanceof Long)edit.putLong(key,(Long)value);else if(value instanceof Float)edit.putFloat(key,(Float)value);else if(value instanceof Set)edit.putStringSet(key,(Set<String>)value);}edit.commit();}
    private View view(String tag){View found=activity.getWindow().getDecorView().findViewWithTag(tag);check(found!=null,"Missing UI tag: "+tag);return found;}
    private void click(String tag){runOnMainSync(()->view(tag).performClick());idle();}
    private void idle(){waitForIdleSync();try{Thread.sleep(350);}catch(InterruptedException interrupted){Thread.currentThread().interrupt();}waitForIdleSync();}
    private void awaitMic(boolean value,long milliseconds)throws Exception{long end=SystemClock.elapsedRealtime()+milliseconds;while(SystemClock.elapsedRealtime()<end){if(prefs.getBoolean("voice_mic_active",false)==value){idle();return;}String status=prefs.getString("voice_status","");if(value&&(status.startsWith("Voice stopped:")||status.startsWith("Microphone could not start:")))throw new AssertionError(status);Thread.sleep(50);}throw new AssertionError("Microphone did not reach "+value+": "+prefs.getString("voice_status",""));}
    private void choose(String text){runOnMainSync(()->((android.view.inputmethod.InputMethodManager)activity.getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(activity.getWindow().getDecorView().getWindowToken(),0));idle();AccessibilityNodeInfo root=null;List<AccessibilityNodeInfo> nodes=java.util.Collections.emptyList();long deadline=SystemClock.elapsedRealtime()+4000;while(SystemClock.elapsedRealtime()<deadline){root=getUiAutomation().getRootInActiveWindow();if(root!=null){nodes=root.findAccessibilityNodeInfosByText(text);if(!nodes.isEmpty())break;}try{Thread.sleep(100);}catch(InterruptedException interrupted){Thread.currentThread().interrupt();break;}}check(root!=null,"Choice dialog absent");check(!nodes.isEmpty(),"Missing choice option: "+text);android.graphics.Rect bounds=new android.graphics.Rect();nodes.get(0).getBoundsInScreen(bounds);check(!bounds.isEmpty(),"Choice option has no visible bounds");long at=SystemClock.uptimeMillis();sendPointerSync(MotionEvent.obtain(at,at,MotionEvent.ACTION_DOWN,bounds.centerX(),bounds.centerY(),0));sendPointerSync(MotionEvent.obtain(at,at+30,MotionEvent.ACTION_UP,bounds.centerX(),bounds.centerY(),0));idle();}
    private void snapshots(Context target)throws Exception {
        VoiceChat.user(target,"ui-visual-chat-fixture","Add bananas and sparkling water.",System.currentTimeMillis()-60000);VoiceChat.assistant(target,"ui-visual-chat-fixture","Added both items.",System.currentTimeMillis()-59000,"answer","");
        VoiceHistory.record(target,new JSONObject().put("task_id","ui-history-fixture").put("text","Add bananas and sparkling water.").put("reply","Added both items.").put("status","completed"));
        prefs.edit().putString("origin","https://assistant.example").putBoolean("wake_enabled",true).putString("voice_status","Listening locally for Hey Chat · experimental").putString("voice_user_text","Add bananas and sparkling water to my shopping list.").putString("voice_reply","Added both items.").putBoolean("voice_mic_active",true).putLong("voice_metrics_elapsed",SystemClock.elapsedRealtime()).putFloat("voice_level",.5f).apply();
        ((android.view.inputmethod.InputMethodManager)target.getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(activity.getWindow().getDecorView().getWindowToken(),0);
        File folder=new File(target.getExternalFilesDir(null),"ui-qa");check(folder.isDirectory()||folder.mkdirs(),"Screenshot directory unavailable");
        for(String page:new String[]{"voice","shopping","activity","settings"}){prefs.edit().putLong("voice_metrics_elapsed",SystemClock.elapsedRealtime()).apply();click("nav_"+page);android.graphics.Bitmap bitmap=getUiAutomation().takeScreenshot();check(bitmap!=null,"Screenshot unavailable");try(OutputStream output=new FileOutputStream(new File(folder,theme+"-"+page+".png"))){check(bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,output),"Screenshot encoding failed");}bitmap.recycle();}
        if(Build.VERSION.SDK_INT>=30){int appearance=activity.getWindow().getInsetsController().getSystemBarsAppearance();check(((appearance&WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS)!=0)==theme.equals("light"),"Wrong light/dark status icon appearance");}
        new File(target.getFilesDir(),"voice-receipts/ui-history-fixture.json").delete();prefs.edit().putString("origin","").putBoolean("wake_enabled",false).putBoolean("voice_mic_active",false).putFloat("voice_level",0f).putString("voice_status","Microphone off").apply();idle();
    }
    private String texts(){StringBuilder result=new StringBuilder();collect(activity.getWindow().getDecorView(),result);return result.toString();}
    private void collect(View view,StringBuilder result){if(!view.isShown())return;if(view instanceof TextView)result.append(((TextView)view).getText()).append('\n');if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int index=0;index<group.getChildCount();index++)collect(group.getChildAt(index),result);}}
    static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
}
