package com.personalassistant.companion;

import android.app.Instrumentation;
import android.content.Context;
import android.os.Bundle;
import java.io.*;
import java.util.*;
import org.json.*;

/** Runs real target-APK Java/native classes under Android. Never calls cloud/API. */
public class VoiceInstrumentation extends Instrumentation {
    @Override public void onCreate(Bundle args){super.onCreate(args);start();}
    @Override public void onStart(){Bundle result=new Bundle();try{
        for(int delay:new int[]{0,16000,48000,160000}){BufferedCapture capture=new BufferedCapture(32000);short[] source=new short[256000];for(int i=0;i<source.length;i++)source[i]=(short)((i*31)^(i>>>4));int trigger=64000;for(int cursor=0;cursor<source.length;cursor+=320){short[] frame=Arrays.copyOfRange(source,cursor,cursor+320);capture.ingest(frame,frame.length);if(cursor+320==trigger)capture.begin(true);if(cursor+320==trigger+delay){short[] snapshot=capture.snapshot();check(Arrays.equals(snapshot,Arrays.copyOfRange(source,trigger-32000,cursor+320)),"Delayed snapshot samples");}}check(Arrays.equals(capture.finish(),Arrays.copyOfRange(source,trigger-32000,source.length)),"Capture gaps/duplication");}result.putBoolean("buffer_delays_0_1_3_10s",true);
        short[] prefix=new short[32000];for(int i=0;i<prefix.length;i++)prefix[i]=(short)((i*31)^(i>>>4));ByteArrayOutputStream assembled=new ByteArrayOutputStream();int chunks=0;VoiceSocket queuedClient=new VoiceSocket(getTargetContext(),new VoiceSocket.Listener(){public void event(JSONObject v){}public void closed(String m,boolean a){}});check(queuedClient.audio(prefix,prefix.length),"Live prefix enqueue failed");java.lang.reflect.Field queueField=VoiceSocket.class.getDeclaredField("output");queueField.setAccessible(true);java.util.List<String> queuedFrames=new java.util.ArrayList<>();((java.util.concurrent.BlockingQueue<String>)queueField.get(queuedClient)).drainTo(queuedFrames);for(String frame:queuedFrames){JSONObject json=new JSONObject(frame);String encoded=json.getString("audio");check(encoded.length()<=44000,"Live prefix exceeds server frame limit");assembled.write(android.util.Base64.decode(encoded,android.util.Base64.DEFAULT));chunks++;}byte[] rawPrefix=assembled.toByteArray();check(rawPrefix.length==prefix.length*2,"Live prefix bytes lost");for(int i=0;i<prefix.length;i++)check(prefix[i]==(short)((rawPrefix[2*i]&255)|(rawPrefix[2*i+1]<<8)),"Live prefix sample order");result.putInt("live_preroll_chunks",chunks);result.putBoolean("live_preroll_frame_limits_exact_order",true);queuedClient.disconnect();check(!queuedClient.audio(prefix,prefix.length),"PCM queued after disconnect");result.putBoolean("closed_live_client_rejects_audio",true);
        Context target=getTargetContext();short[] positive=pcm(getContext(),"positive.pcm");WakeDetector detector=null;try{detector=(WakeDetector)Class.forName("com.personalassistant.companion.SherpaWakeDetector",true,target.getClassLoader()).getMethod("create",Context.class).invoke(null,target);}catch(ClassNotFoundException ignored){}boolean nativeDetector=detector!=null&&detector.available();if(!nativeDetector){TemplateWakeDetector fallback=new TemplateWakeDetector();fallback.add(pcm(getContext(),"template.pcm"));fallback.threshold(.15);detector=fallback;}int activations=0,firstTrigger=-1;BufferedCapture triggeredCapture=new BufferedCapture(32000);short[] padded=new short[positive.length+32000];System.arraycopy(positive,0,padded,16000,positive.length);for(int cursor=0;cursor<padded.length;cursor+=320){short[] frame=Arrays.copyOfRange(padded,cursor,Math.min(padded.length,cursor+320));triggeredCapture.ingest(frame,frame.length);if(detector.accept(frame,frame.length)){activations++;if(firstTrigger<0){firstTrigger=cursor+frame.length;triggeredCapture.begin(true);}}}detector.close();check(activations>0,"Positive fixture wake not detected");check(Arrays.equals(triggeredCapture.finish(),Arrays.copyOfRange(padded,Math.max(0,firstTrigger-32000),padded.length)),"Native wake to buffered command lost samples");result.putBoolean("native_wake_buffer_exact_order",true);result.putInt("positive_trigger_sample",firstTrigger-16000);result.putString("wake_engine",nativeDetector?"sherpa-native":"template-test-only");result.putInt("positive_activations",activations);
        if(nativeDetector){WakeDetector negativeDetector=(WakeDetector)Class.forName("com.personalassistant.companion.SherpaWakeDetector",true,target.getClassLoader()).getMethod("create",Context.class).invoke(null,target);short[] negative=pcm(getContext(),"negative.pcm");short[] silencePadded=new short[negative.length+32000];System.arraycopy(negative,0,silencePadded,16000,negative.length);int falseWakes=0;for(int cursor=0;cursor<silencePadded.length;cursor+=320){short[] frame=Arrays.copyOfRange(silencePadded,cursor,Math.min(silencePadded.length,cursor+320));if(negativeDetector.accept(frame,frame.length))falseWakes++;}negativeDetector.close();check(falseWakes==0,"Original no-wake negative false activation");result.putInt("negative_activations",falseWakes);}
        boundaryGate();result.putBoolean("stale_split_prefix_rejected",true);
        if(nativeDetector){nativeBoundary(target,positive,result);}
        String id=VoiceOutbox.save(target,positive,"instrumentation-only",true);File file=new File(VoiceOutbox.directory(target),id+".json");JSONObject saved=new JSONObject(VoiceOutbox.read(file));check(id.equals(saved.getString("id"))&&saved.getBoolean("dry_run"),"Durable envelope");byte[] wav=android.util.Base64.decode(saved.getString("audio_base64"),android.util.Base64.DEFAULT);check(wav.length==44+positive.length*2&&new String(wav,0,4,"US-ASCII").equals("RIFF"),"WAV format");check(file.delete(),"Fixture cleanup");result.putBoolean("durable_voice_envelope",true);
        check(Cloud.prefs(target).getString("token","").isEmpty(),"Foreground test requires an unpaired disposable emulator");
        try(android.os.ParcelFileDescriptor shell=getUiAutomation().executeShellCommand("pm grant com.personalassistant.companion android.permission.RECORD_AUDIO")){try(InputStream in=new android.os.ParcelFileDescriptor.AutoCloseInputStream(shell)){while(in.read()!=-1){}}}
        android.app.Activity activity=startActivitySync(new android.content.Intent(target,MainActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));
        runOnMainSync(()->target.startForegroundService(new android.content.Intent(target,VoiceService.class)));
        String voiceState="";long deadline=System.currentTimeMillis()+15000;while(System.currentTimeMillis()<deadline){voiceState=Cloud.prefs(target).getString("voice_status","");if(voiceState.equals("Ready for voice")||voiceState.startsWith("Listening locally")||voiceState.startsWith("Voice stopped:")||voiceState.startsWith("Microphone could not start:"))break;Thread.sleep(200);}check(voiceState.equals("Ready for voice")||voiceState.startsWith("Listening locally"),"Foreground microphone never became ready: "+voiceState);
        runOnMainSync(()->{target.stopService(new android.content.Intent(target,VoiceService.class));activity.finish();});result.putString("foreground_microphone",voiceState);
        result.putString("stream","Android runtime capture, wake boundary, durable envelope and virtual microphone readiness passed; no cloud/API calls.");finish(0,result);
    }catch(Throwable error){result.putString("stream",android.util.Log.getStackTraceString(error));finish(1,result);}}
    static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
    static final class PrefixDetector implements WakeDetector {
        boolean prefix;int resets;
        public boolean accept(short[] data,int size){boolean found=false;for(int i=0;i<size;i++){if(prefix&&data[i]==200)found=true;prefix=data[i]==100;}return found;}
        public void reset(){prefix=false;resets++;}public boolean available(){return true;}public String name(){return "Boundary fixture";}
    }
    static void boundaryGate(){PrefixDetector unsafe=new PrefixDetector();unsafe.accept(new short[]{100},1);check(unsafe.accept(new short[]{200},1),"Stale prefix control missing");PrefixDetector safe=new PrefixDetector();WakeStreamGate gate=new WakeStreamGate(safe);gate.accept(new short[]{100},1);gate.pause();gate.pause();check(!gate.accept(new short[]{200},1),"Wake crossed skipped audio");check(safe.resets==1,"Repeated suppression reloaded context");check(gate.accept(new short[]{100,200},2),"Contiguous wake failed after reset");}
    static void nativeBoundary(Context target,short[] positive,Bundle result)throws Exception {
        Class<?> factory=Class.forName("com.personalassistant.companion.SherpaWakeDetector",true,target.getClassLoader());
        WakeDetector detector=(WakeDetector)factory.getMethod("create",Context.class).invoke(null,target),fresh=(WakeDetector)factory.getMethod("create",Context.class).invoke(null,target);
        try{java.lang.reflect.Field model=factory.getDeclaredField("spotter"),stream=factory.getDeclaredField("stream");model.setAccessible(true);stream.setAccessible(true);Object weights=model.get(detector),oldStream=stream.get(detector);WakeStreamGate gate=new WakeStreamGate(detector);int split=Math.min(32000,(positive.length/640)*320);
            for(int cursor=0;cursor<split;cursor+=320)gate.accept(Arrays.copyOfRange(positive,cursor,cursor+320),320);
            gate.pause();List<Integer> resumed=new ArrayList<>(),pristine=new ArrayList<>();short[] suffix=new short[positive.length-split+16000];System.arraycopy(positive,split,suffix,0,positive.length-split);
            for(int cursor=0;cursor<suffix.length;cursor+=320){short[] frame=Arrays.copyOfRange(suffix,cursor,Math.min(suffix.length,cursor+320));if(gate.accept(frame,frame.length))resumed.add(cursor+frame.length);if(fresh.accept(frame,frame.length))pristine.add(cursor+frame.length);}
            check(model.get(detector)==weights,"Stream boundary reloaded model weights");check(stream.get(detector)!=oldStream,"Native acoustic stream survived gap");check(resumed.equals(pristine),"Old native prefix changed post-gap wake decisions");result.putBoolean("native_gap_matches_fresh_suffix",true);result.putBoolean("native_reset_retains_model_weights",true);result.putInt("native_gap_suffix_activations",resumed.size());
        }finally{detector.close();fresh.close();}
    }
    static short[] pcm(Context context,String path)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=context.getAssets().open(path)){byte[] bytes=new byte[8192];int n;while((n=in.read(bytes))!=-1)out.write(bytes,0,n);}byte[] raw=out.toByteArray();short[] pcm=new short[raw.length/2];for(int i=0;i<pcm.length;i++)pcm[i]=(short)((raw[2*i]&255)|(raw[2*i+1]<<8));return pcm;}
}
