'use strict';
const $=id=>document.getElementById(id), base='/groceries/', client=location.origin+base;
let snapshot=JSON.parse(localStorage.getItem('groceries-cache')||'{"items":[],"recipes":[]}'), queue=JSON.parse(localStorage.getItem('groceries-outbox')||'[]'), failures=JSON.parse(localStorage.getItem('groceries-review')||'[]'), tokens=JSON.parse(localStorage.getItem('groceries-login')||'null'), syncing=false, refreshPromise=null, editing=null;
const uuid=()=>crypto.randomUUID(), saveQueue=()=>localStorage.setItem('groceries-outbox',JSON.stringify(queue));
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6500)}
function theme(){const current=document.documentElement.dataset.theme||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');document.documentElement.dataset.theme=current==='dark'?'light':'dark';localStorage.setItem('groceries-theme',document.documentElement.dataset.theme)}
document.documentElement.dataset.theme=localStorage.getItem('groceries-theme')||'';$('theme').onclick=theme;
function signIn(){const state=uuid();sessionStorage.setItem('groceries-state',JSON.stringify({state,time:Date.now()}));location.href=location.origin+'/auth/authorize?'+new URLSearchParams({client_id:client,redirect_uri:client,response_type:'code',state})}
async function exchange(body){const r=await fetch('/auth/token',{method:'POST',body:new URLSearchParams({...body,client_id:client})});if(!r.ok)throw Error('Sign-in was not completed.');const result=await r.json();tokens={...result,refresh_token:result.refresh_token||body.refresh_token};tokens.expires_at=Date.now()+tokens.expires_in*1000;localStorage.setItem('groceries-login',JSON.stringify(tokens));return tokens}
async function access(){if(!tokens)throw Error('Sign in to sync with your cloud list.');if(tokens.expires_at<Date.now()+60000){if(!refreshPromise)refreshPromise=exchange({grant_type:'refresh_token',refresh_token:tokens.refresh_token}).finally(()=>refreshPromise=null);await refreshPromise}return tokens.access_token}
async function api(path,body){const token=await access(),r=await fetch(base+'v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(r.status===401){localStorage.removeItem('groceries-login');tokens=null;throw Error('Please sign in again.')}if(!r.ok){let detail='Cloud request failed.';try{const data=await r.json();detail=typeof data.detail==='string'?data.detail:'Please check the recipe fields.'}catch{}const error=Error(detail);error.status=r.status;throw error}return r.json()}
function connection(message){$('connection').textContent=message;$('pending').textContent=queue.length?queue.length+' change'+(queue.length===1?'':'s')+' saved on this phone':'';$('signin').textContent=tokens?'Sign out':'Sign in'}
function persist(){localStorage.setItem('groceries-cache',JSON.stringify(snapshot));saveQueue()}
async function sync(){if(syncing)return;syncing=true;try{if(!navigator.onLine)throw Error('Offline · changes are saved on this phone.');if(!tokens)throw Error('Sign in · local changes will wait on this phone.');connection('Syncing…');while(queue.length){const change=queue[0];try{await api('mutations',change)}catch(error){if([409,422].includes(error.status)){failures.push({change,error:error.message});localStorage.setItem('groceries-review',JSON.stringify(failures));queue.shift();saveQueue();toast('A change needs review. Your original entry is still saved on this phone.');continue}throw error}queue.shift();saveQueue()}snapshot=await api('list');persist();render();connection('Cloud saved · works while the laptop is asleep')}catch(error){connection(error.message);render()}finally{syncing=false}}
function enqueue(value){queue.push({id:uuid(),created_at:new Date().toISOString(),...value});saveQueue();render();sync()}
function split(text){const compounds=new Map();for(const phrase of ['mac and cheese','salt and pepper','oil and vinegar']){const key='COMPOUND'+compounds.size;if(new RegExp(phrase,'i').test(text)){compounds.set(key,phrase);text=text.replace(new RegExp(phrase,'ig'),key)}}return text.split(/\s*(?:,|;|\band\b|\bund\b)\s*/i).map(x=>x.trim()).filter(Boolean).map(x=>compounds.get(x)||x)}
function render(){const optimistic=snapshot.items.map(x=>({...x}));for(const pending of queue){if(pending.operation==='add')for(const [i,item] of pending.items.entries())optimistic.push({...item,id:'pending-'+pending.id+'-'+i,complete:0,version:0});if(pending.operation==='complete'){const item=optimistic.find(x=>x.id===pending.target);if(item)item.complete=pending.complete}if(pending.operation==='delete'){const i=optimistic.findIndex(x=>x.id===pending.target);if(i>=0)optimistic.splice(i,1)}}$('shopping').replaceChildren();$('completed').replaceChildren();for(const item of optimistic){const row=el('div',undefined,'item'+(item.complete?' completed':'')), check=el('button',item.complete?'✓':'','check');check.setAttribute('aria-label',(item.complete?'Restore ':'Mark bought: ')+item.name);check.disabled=!item.version||queue.some(x=>x.target===item.id);check.onclick=()=>enqueue({operation:'complete',target:item.id,version:item.version,complete:!item.complete});const copy=el('div',undefined,'copy');copy.append(el('div',item.name,'name'));if(item.quantity)copy.append(el('div',item.quantity,'quantity'));const search=el('a','REWE');search.href='https://shop.rewe.de/productList?search='+encodeURIComponent(item.name);search.target='_blank';search.rel='noopener noreferrer';search.title='Search products; availability depends on the selected store';const remove=el('button','×','remove');remove.setAttribute('aria-label','Remove '+item.name);remove.disabled=check.disabled;remove.onclick=()=>enqueue({operation:'delete',target:item.id,version:item.version});row.append(check,copy,search,remove);$(item.complete?'completed':'shopping').append(row)}if(!optimistic.some(x=>!x.complete))$('shopping').append(el('p','Your list is clear. Add something above.','empty'));$('bought').hidden=!optimistic.some(x=>x.complete);$('store').replaceChildren();if(snapshot.store?.name){$('store').append(el('strong',snapshot.store.name),el('p',snapshot.store.address));const a=el('a','Store details ↗');if(/^https:\/\/www\.rewe\.de\//.test(snapshot.store.url)){a.href=snapshot.store.url;a.target='_blank';a.rel='noopener noreferrer';$('store').append(a)}$('store').append(el('p','Product links open REWE search. Stock at this branch has not been verified.','hint'))}else $('store').append(el('p','REWE store details will appear after syncing.'));renderRecipes();$('pending').textContent=queue.length?queue.length+' changes saved on this phone':''}
function renderRecipes(){const recipes=new Map(snapshot.recipes.map(x=>[x.id,x]));for(const change of queue)if(change.operation==='recipe_save')recipes.set(change.recipe.id,{...change.recipe,version:change.version||0,pending:true});$('recipe-list').replaceChildren();for(const recipe of recipes.values()){const card=el('article',undefined,'recipe');card.append(el('h3',recipe.title),el('p',recipe.ingredients.length+' ingredients'+(recipe.pending?' · saved on this phone':''),'hint'));const detail=el('details'),summary=el('summary','Ingredients & method'),text=el('pre',recipe.ingredients.map(x=>[x.quantity,x.name].filter(Boolean).join(' ')).join('\n')+'\n\n'+recipe.instructions);detail.append(summary,text);const selection=el('div',undefined,'ingredients-choice'),checks=recipe.ingredients.map(item=>{const label=el('label'),check=el('input');check.type='checkbox';check.checked=true;label.append(check,document.createTextNode(' '+[item.quantity,item.name].filter(Boolean).join(' ')));selection.append(label);return check});const actions=el('div',undefined,'actions'),add=el('button','Add selected ingredients');add.onclick=()=>{const items=recipe.ingredients.filter((_,index)=>checks[index].checked);if(items.length)enqueue({operation:'add',items});else toast('Choose at least one ingredient.')};card.append(selection);const edit=el('button','Edit','subtle');edit.disabled=recipe.pending;edit.onclick=()=>openRecipe(recipe);actions.append(add,edit);if(/^https?:\/\//.test(recipe.source)){const a=el('a','Original recipe ↗');a.href=recipe.source;a.target='_blank';a.rel='noopener noreferrer';card.append(a)}card.append(detail,actions);$('recipe-list').append(card)}if(!recipes.size)$('recipe-list').append(el('p','No recipes saved yet. Paste ingredients from AnyList or add your own.','empty'))}
function openRecipe(recipe){editing=recipe||null;$('recipe-editor').hidden=false;$('recipe-title').value=recipe?.title||'';$('recipe-ingredients').value=recipe?.ingredients.map(x=>[x.quantity,x.name].filter(Boolean).join(' ')).join('\n')||'';$('recipe-instructions').value=recipe?.instructions||'';$('recipe-source').value=recipe?.source||'';$('recipe-title').focus()}
$('new-recipe').onclick=()=>openRecipe();$('cancel-recipe').onclick=()=>$('recipe-editor').hidden=true;
$('add').onsubmit=e=>{e.preventDefault();const names=split($('items').value);if(!names.length)return;enqueue({operation:'add',items:names.map(name=>({name,quantity:''}))});$('items').value=''};
$('recipe-editor').onsubmit=e=>{e.preventDefault();const ingredients=$('recipe-ingredients').value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const m=line.match(/^([\d.,/½¼¾]+\s*(?:g|kg|ml|l|tbsp|tsp|cups?|pieces?)?\s+)\s*(.+)$/i);return m?{quantity:m[1].trim(),name:m[2]}:{quantity:'',name:line}});if(!ingredients.length)return;enqueue({operation:'recipe_save',...(editing?{version:editing.version}:{}),recipe:{id:editing?.id||uuid(),title:$('recipe-title').value.trim(),ingredients,instructions:$('recipe-instructions').value,source:$('recipe-source').value}});$('recipe-editor').hidden=true};
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===button));$('list').hidden=button.dataset.tab!=='list';$('recipes').hidden=button.dataset.tab!=='recipes'});
$('signin').onclick=()=>{if(!tokens)return signIn();if(queue.length&&!confirm('There are unsynced changes on this phone. Sign out and keep them here?'))return;localStorage.removeItem('groceries-login');tokens=null;connection('Signed out · your local list remains on this phone.');};
window.addEventListener('online',sync);window.addEventListener('offline',()=>connection('Offline · changes are saved on this phone.'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
function review(){let panel=$('review');if(!panel){panel=el('details');panel.id='review';$('connection').after(panel)}panel.replaceChildren();panel.hidden=!failures.length;panel.append(el('summary',failures.length+' saved changes need review'));for(const [index,failure] of failures.entries()){const card=el('article',undefined,'recipe'),change=failure.change;card.append(el('p',failure.error),el('pre',change.recipe?change.recipe.title+'\n'+change.recipe.ingredients.map(x=>[x.quantity,x.name].filter(Boolean).join(' ')).join('\n'):(change.items||[]).map(x=>x.name).join(', ')||'Shopping item changed on another device.'));const retry=el('button','Retry with current list');retry.onclick=()=>{const next={...change,id:uuid()};const row=snapshot.items.find(x=>x.id===next.target)||snapshot.recipes.find(x=>x.id===(next.recipe?.id||next.target));if(row)next.version=row.version;failures.splice(index,1);localStorage.setItem('groceries-review',JSON.stringify(failures));queue.push(next);saveQueue();review();sync()};const discard=el('button','Discard','subtle');discard.onclick=()=>{if(!confirm('Discard this saved change?'))return;failures.splice(index,1);localStorage.setItem('groceries-review',JSON.stringify(failures));review()};card.append(retry,discard);panel.append(card)}}
const originalRender=render;render=()=>{originalRender();review()};
(async()=>{const params=new URLSearchParams(location.search);if(params.has('code')){const expected=JSON.parse(sessionStorage.getItem('groceries-state')||'null');const code=params.get('code');history.replaceState(null,'',base);sessionStorage.removeItem('groceries-state');try{if(!expected||params.get('state')!==expected.state||Date.now()-expected.time>600000)throw Error('Sign-in session expired. Try again.');await exchange({grant_type:'authorization_code',code})}catch(error){toast(error.message)}}render();await sync();if('serviceWorker'in navigator)navigator.serviceWorker.register(base+'sw.js',{scope:base}).catch(()=>{});setInterval(sync,30000)})();

$('pair-phone').onclick=async()=>{try{const paired=await api('mobile/pairing',{});let panel=$('phone-setup');if(!panel){panel=el('section');panel.id='phone-setup';document.querySelector('main').append(panel)}panel.replaceChildren(el('h2','Phone widget & alarms'),el('p','Install the companion, then enter this server address and the code. The code expires in 10 minutes.'),el('p',location.origin),el('pre',paired.code));const download=el('a','Download Android companion');download.href=base+'v1/mobile/companion.apk';panel.append(download);panel.scrollIntoView({behavior:'smooth'})}catch(error){toast(error.message)}};

let importBody=null;
$('import-content').oninput=$('import-source').oninput=()=>{importBody=null;$('commit-import').hidden=true};
$('preview-import').onclick=async()=>{try{const body={content:$('import-content').value,format:'auto',source:$('import-source').value};const preview=await api('recipes/import/preview',body);importBody=body;$('import-preview').replaceChildren(el('p',preview.count+' recipe'+(preview.count===1?'':'s')));for(const recipe of preview.recipes){const card=el('article',undefined,'recipe');card.append(el('h3',recipe.title),el('pre',recipe.ingredients.map(x=>[x.quantity,x.name].filter(Boolean).join(' ')).join('\n')+'\n\n'+recipe.instructions));$('import-preview').append(card)}for(const warning of preview.warnings)$('import-preview').append(el('p',warning,'hint'));$('commit-import').hidden=false}catch(error){toast(error.message)}};
$('commit-import').onclick=async()=>{if(!importBody)return;try{const saved=await api('recipes/import/commit',importBody);toast('Imported '+saved.saved_ids.length+' recipes. Choose ingredients to add to your list.');importBody=null;$('commit-import').hidden=true;await sync()}catch(error){toast(error.message)}};
