package com.personalassistant.companion;

import android.app.*;
import android.app.role.RoleManager;
import android.content.*;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.*;
import android.provider.*;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.DateFormat;
import java.util.*;

/** Voice-first native companion. Background updates never reconstruct an input form. */
public class MainActivity extends Activity {
    private AppUi ui;private LinearLayout body,listRows,historyRows,pairBox;
    private final LinearLayout[] pages=new LinearLayout[4];private AppUi.NavBar navBar;private AppUi.VoiceButton talk;private boolean orbLive;
    private ChatTimeline chat;private Button conversationButton;private boolean resumed;
    private String listKey="",historyKey="";private int selected;private boolean registered,refreshQueued,changing,pairBusy,syncBusy,updateBusy;
    private final Handler handler=new Handler(Looper.getMainLooper());
    TextView status,voiceStatus,voiceTranscript;
    private TextView connection,voiceDetail,answer,partial,testCount,pairStatus,accountStatus,updateStatus,setupStatus,historyStatus;
    private EditText input,server,code;private Button connect,testButton,install,resumeListening,retryVoice,stopMicrophone;private Switch background;private View testCard;
    private ProgressBar starting,pairProgress;private AppUi.Meter meter;
    private final SharedPreferences.OnSharedPreferenceChangeListener prefsListener=(p,key)->{if("voice_level".equals(key)){if(meter!=null)meter.value(AppUi.level(this),AppUi.micActive(this));if(talk!=null)talk.level(AppUi.level(this),orbLive&&AppUi.micActive(this));return;}if(!refreshQueued){refreshQueued=true;handler.postDelayed(()->{refreshQueued=false;if(!isDestroyed())show();},80);}};
    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent intent){show();if("com.personalassistant.companion.GROCERY_STATE".equals(intent.getAction()))renderList();}};
    @Override public void onCreate(Bundle saved){AppUi.theme(this);super.onCreate(saved);ui=new AppUi(this);ui.window();build();if(saved!=null){selected=saved.getInt("tab",0);input.setText(saved.getString("draft",""));server.setText(saved.getString("server",server.getText().toString()));code.setText(saved.getString("code",""));}select(selected);if(Intent.ACTION_SEND.equals(getIntent().getAction())){select(1);share(getIntent().getStringExtra(Intent.EXTRA_TEXT));}if(paired()){sync();PushRegistration.start(this);TaskSyncJob.schedule(this,true);}checkUpdates(false);openTaskIntent(getIntent());}
    @Override public void onSaveInstanceState(Bundle state){state.putInt("tab",selected);state.putString("draft",input.getText().toString());state.putString("server",server.getText().toString());state.putString("code",code.getText().toString());super.onSaveInstanceState(state);}
    @Override public void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(Intent.ACTION_SEND.equals(intent.getAction())){select(1);share(intent.getStringExtra(Intent.EXTRA_TEXT));}else if(!openTaskIntent(intent))select(0);if(paired())sync();}
    @Override public void onStart(){super.onStart();IntentFilter filter=new IntentFilter("com.personalassistant.companion.VOICE_STATE");filter.addAction("com.personalassistant.companion.GROCERY_STATE");filter.addAction("com.personalassistant.companion.TASK_STATE");if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,filter);registered=true;Cloud.prefs(this).registerOnSharedPreferenceChangeListener(prefsListener);show();}
    @Override public void onResume(){super.onResume();resumed=true;if(ui!=null){ui.window();show();checkUpdates(false);if(paired())TaskSyncJob.schedule(this,false);}}
    @Override public void onPause(){resumed=false;super.onPause();}
    @Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(focus&&ui!=null)ui.window();}
    @Override public void onDestroy(){NativeTaskScreens.close(this);Updates.dismissPrompt(this);super.onDestroy();}
    @Override public void onStop(){if(registered){unregisterReceiver(receiver);registered=false;}Cloud.prefs(this).unregisterOnSharedPreferenceChangeListener(prefsListener);super.onStop();}
    private boolean paired(){SharedPreferences p=Cloud.prefs(this);return !p.getString("token","").isEmpty()&&!p.getString("status","").startsWith("Disconnected.");}
    private void safe(Runnable action){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())action.run();});}
    private Button action(LinearLayout box,String label,boolean primary,Runnable callback){Button button=ui.button(label,primary,callback);box.addView(button,new LinearLayout.LayoutParams(-1,-2));return button;}
    private void heading(LinearLayout page,String title,String detail){page.addView(ui.text(title,29,true));ui.space(page,7);page.addView(ui.detail(detail));ui.space(page,27);}
    private void build(){LinearLayout root=ui.column();root.setFitsSystemWindows(true);root.setBackground(ui.backgroundDrawable());body=ui.column();root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        for(int i=0;i<4;i++){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);pages[i]=ui.column();pages[i].setPadding(ui.dp(24),ui.dp(22),ui.dp(24),ui.dp(24));scroll.addView(pages[i]);body.addView(scroll,new LinearLayout.LayoutParams(-1,-1));}
        buildVoice();buildShopping();buildActivity();buildSettings();navBar=ui.navBar(new String[]{"Voice","Shopping","Activity","Settings"},new String[]{"voice","shopping","activity","settings"},new String[]{"nav_voice","nav_shopping","nav_activity","nav_settings"},this::select);root.addView(navBar,navBar.params());setContentView(root);}
    private void select(int index){int previous=selected;selected=index;for(int i=0;i<4;i++){boolean entering=i==index&&body.getChildAt(i).getVisibility()!=View.VISIBLE;body.getChildAt(i).setVisibility(i==index?View.VISIBLE:View.GONE);if(entering)AppUi.slide(body.getChildAt(i),index>previous?1:-1);}navBar.select(index,true);if(index==1)renderList();if(index==2)renderHistory();show();}
    private void buildVoice(){
        LinearLayout page=pages[0],top=ui.row();top.addView(ui.text("Voice",29,true),new LinearLayout.LayoutParams(0,-2,1));connection=ui.badge("Connect phone");connection.setOnClickListener(v->{select(3);if(!paired())code.requestFocus();});top.addView(connection);page.addView(top);ui.space(page,9);page.addView(ui.detail("One request at a time. Start a conversation when you need more."));
        LinearLayout hero=ui.column();hero.setGravity(Gravity.CENTER_HORIZONTAL);ui.space(hero,12);talk=ui.voiceButton(()->{if(!paired()){select(3);code.requestFocus();Toast.makeText(this,"Connect your phone first",Toast.LENGTH_SHORT).show();return;}if(Cloud.prefs(this).getBoolean("voice_listening_test",false))finishTest();startVoice(true);});talk.setTag("talk");hero.addView(talk,new LinearLayout.LayoutParams(ui.dp(244),ui.dp(244)));ui.space(hero,8);
        LinearLayout state=ui.row();state.setGravity(Gravity.CENTER);starting=new ProgressBar(this);LinearLayout.LayoutParams spin=new LinearLayout.LayoutParams(ui.dp(16),ui.dp(16));spin.rightMargin=ui.dp(8);state.addView(starting,spin);voiceStatus=ui.text("Microphone off",15,true);voiceStatus.setTag("voice_status");voiceStatus.setTextColor(ui.accent);state.addView(voiceStatus);hero.addView(state);ui.space(hero,6);voiceDetail=ui.detail("Tap Talk to start.");voiceDetail.setGravity(Gravity.CENTER);hero.addView(voiceDetail,new LinearLayout.LayoutParams(-1,-2));meter=new AppUi.Meter(this,ui.accent);meter.setTag("voice_level");LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(ui.dp(150),ui.dp(25));mp.topMargin=ui.dp(10);hero.addView(meter,mp);resumeListening=ui.quietButton("Resume listening",()->startVoice(false));resumeListening.setTag("resume_listening");hero.addView(resumeListening);stopMicrophone=ui.stopButton("Stop microphone",this::stopMic);stopMicrophone.setTag("stop_microphone");hero.addView(stopMicrophone);ui.space(hero,13);page.addView(hero);
        LinearLayout listen=ui.card();background=ui.toggle("Background listening","Hey Chat, even while your phone is locked.",listen,false,(button,on)->{if(!changing)setBackground(on);});background.setTag("background_listening");ui.divider(listen);LinearLayout links=ui.row();Button setup=ui.quietButton("Phone setup",()->select(3));links.addView(setup,new LinearLayout.LayoutParams(0,-2,1));testButton=ui.quietButton("Test wake",this::toggleTest);testButton.setTag("test_wake");links.addView(testButton,new LinearLayout.LayoutParams(0,-2,1));listen.addView(links);page.addView(listen);
        conversationButton=ui.quietButton("Start conversation",this::toggleConversation);conversationButton.setTag("conversation_mode");page.addView(conversationButton);TextView modeHelp=ui.detail("Say Start conversation mode to keep talking. Say That was all to finish.");modeHelp.setTextSize(12);modeHelp.setGravity(Gravity.CENTER);page.addView(modeHelp);ui.space(page,18);
        LinearLayout test=ui.card();test.addView(ui.badge("LOCAL TEST"));ui.space(test,12);test.addView(ui.text("Say Hey Chat normally",18,true));ui.space(test,7);test.addView(ui.detail("Try your usual volume, then lock the phone. No commands or API calls are sent."));ui.space(test,14);testCount=ui.text("Waiting for a wake...",14,true);test.addView(testCount);ui.space(test,6);partial=ui.detail("No words detected yet.");test.addView(partial);ui.divider(test);action(test,"Adjust sensitivity",false,this::sensitivity).setTag("test_sensitivity");testCard=test;page.addView(test);
        ui.label(page,"CONVERSATION");chat=new ChatTimeline(ui);page.addView(chat.rows);voiceTranscript=ui.text("",15,false);answer=ui.text("",15,false);
    }
    private void buildShopping(){LinearLayout page=pages[1];heading(page,"Shopping","Your list, wherever you are.");LinearLayout add=ui.row();input=ui.field("Add an item","");input.setTag("shopping_item");input.setImeOptions(EditorInfo.IME_ACTION_DONE);input.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_DONE){addItem();return true;}return false;});add.addView(input,new LinearLayout.LayoutParams(0,ui.dp(54),1));Button save=ui.button("+",true,this::addItem);save.setTextSize(25);save.setContentDescription("Add to list");save.setTag("shopping_add");LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(ui.dp(54),ui.dp(54));ap.leftMargin=ui.dp(9);add.addView(save,ap);page.addView(add);ui.space(page,10);LinearLayout tools=ui.row();tools.addView(ui.quietButton("Refresh",this::sync),new LinearLayout.LayoutParams(0,-2,1));tools.addView(ui.quietButton("Recipes",()->RecipeLibrary.show(this,this::sync,this::share,()->openWeb("/groceries/"))),new LinearLayout.LayoutParams(0,-2,1));page.addView(tools);ui.space(page,12);status=ui.detail("");status.setTextSize(12);status.setTag("shopping_status");page.addView(status);ui.space(page,14);listRows=ui.column();page.addView(listRows);ui.space(page,13);action(page,"Review saved changes",false,this::review);}
    private void buildActivity(){LinearLayout page=pages[2];heading(page,"Activity","Recent requests and answers.");historyStatus=ui.detail("");historyStatus.setTextSize(12);page.addView(historyStatus);ui.space(page,14);retryVoice=action(page,"Send saved voice commands",false,()->{VoiceOutbox.retry(this,null);Toast.makeText(this,"Checking saved commands",Toast.LENGTH_SHORT).show();});retryVoice.setTag("retry_voice");historyRows=ui.column();page.addView(historyRows);ui.space(page,24);LinearLayout history=ui.card();action(history,"All task history",false,this::taskHistory).setTag("activity_history");history.addView(ui.detail("Full answers and follow-ups, here in Companion."));page.addView(history);}
    private Button setting(LinearLayout group,String title,String icon,Runnable callback){Button button=ui.actionRow(title,icon,callback);group.addView(button,new LinearLayout.LayoutParams(-1,-2));return button;}
    private void buildSettings(){LinearLayout page=pages[3];heading(page,"Settings","Voice, connection and phone setup.");ui.label(page,"PHONE SETUP");LinearLayout setup=ui.card();setup.setPadding(ui.dp(9),ui.dp(9),ui.dp(9),ui.dp(14));setting(setup,"Microphone permission","voice",()->requestMic(false));setting(setup,"Digital assistant","settings",this::chooseAssistant);setting(setup,"Battery settings","activity",()->openSettings(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));ui.divider(setup);setupStatus=ui.detail("");setupStatus.setTextSize(12);setup.addView(setupStatus);ui.space(setup,7);setup.addView(ui.detail("Choose Unrestricted for battery. Enable Background listening, wait until ready, then lock your phone."));page.addView(setup);
        ui.label(page,"VOICE & APPEARANCE");LinearLayout modes=ui.card();modes.addView(ui.detail("Hey Chat handles one command, then returns to standby. Start conversation mode keeps listening until you say That was all."));ui.divider(modes);ui.toggle("Transcription preview","Show words without executing commands.",modes,Cloud.prefs(this).getBoolean("voice_preview",false),(b,on)->Cloud.prefs(this).edit().putBoolean("voice_preview",on).apply()).setTag("transcription_preview");ui.divider(modes);setting(modes,"Wake sensitivity","voice",this::sensitivity).setTag("wake_sensitivity");setting(modes,"Light, dark or system","settings",this::appearance).setTag("appearance");page.addView(modes);
        ui.label(page,"ACCOUNT");LinearLayout account=ui.card();accountStatus=ui.detail("");account.addView(accountStatus);TextView pushState=ui.detail(Cloud.prefs(this).getString("push_status","Notification connection will be set up after pairing."));pushState.setTag("push_status");pushState.setTextSize(12);ui.space(account,7);account.addView(pushState);ui.space(account,13);pairBox=ui.column();server=ui.field("HTTPS server address",Cloud.prefs(this).getString("origin",""));server.setTag("server_address");server.setContentDescription("Server address");server.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);pairBox.addView(server);ui.space(pairBox,10);code=ui.field("One-use pairing code","");code.setTag("pairing_code");code.setContentDescription("Pairing code");code.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);pairBox.addView(code);ui.space(pairBox,10);pairStatus=ui.detail("Get a new pairing code from your dashboard.");pairStatus.setTextSize(12);pairStatus.setTag("pairing_status");pairBox.addView(pairStatus);ui.space(pairBox,12);pairProgress=new ProgressBar(this);pairProgress.setVisibility(View.GONE);pairBox.addView(pairProgress,new LinearLayout.LayoutParams(-1,ui.dp(26)));connect=action(pairBox,"Connect phone",true,this::pair);connect.setTag("pair");account.addView(pairBox);ui.space(account,5);setting(account,"Disconnect phone","settings",this::disconnect);page.addView(account);
        ui.label(page,"APP & SHORTCUTS");LinearLayout updates=ui.card();updateStatus=ui.detail("");updateStatus.setTextSize(12);updateStatus.setTag("update_status");updates.addView(updateStatus);ui.space(updates,7);setting(updates,"Check for updates","activity",()->checkUpdates(true));install=action(updates,"Install update",true,()->Updates.install(this));install.setTag("install_update");setting(updates,"Notifications","activity",()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},301);else openSettings(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));});setting(updates,"Microphone Quick Settings tile","voice",this::addMicrophoneTile).setTag("add_mic_tile");ui.divider(updates);updates.addView(ui.detail("Shopping widget: long press your Home screen, then Widgets. Task details and follow-ups open in Companion."));page.addView(updates);
    }
    void show(){if(ui==null||voiceStatus==null)return;SharedPreferences p=Cloud.prefs(this);boolean mic=AppUi.micActive(this),test=p.getBoolean("voice_listening_test",false),wake=p.getBoolean("wake_enabled",false);String raw=p.getString("voice_status","Microphone off"),low=raw.toLowerCase(Locale.ROOT);boolean loading=low.contains("starting")||low.contains("preparing")||low.contains("loading");String title,detail;
        if(wake&&!mic&&!loading){title=test?"Wake test paused":"Listening paused";detail="Background listening is enabled, but the microphone is off. Resume to restart it.";}else if(test){title=loading?"Getting ready...":"Wake test";detail="Local only. Say Hey Chat at your normal volume.";}else if(loading){title="Getting ready...";detail="The microphone and wake model are starting.";}else if(low.contains("sending")||low.contains("connecting live")){title="Connecting...";detail="Your audio is buffered while the connection starts.";}else if(low.contains("no internet")||low.contains("saved on this phone")||low.contains("cloud unavailable")){title=VoiceOutbox.pending(this)>0?"Saved offline":wake&&mic?"Listening offline":"Offline";detail=raw;}else if(low.contains("permission")||low.contains("interrupted")||low.contains("could not")||low.contains("unavailable")||low.contains("voice stopped")||low.contains("connection lost")){title="Needs attention";detail=raw;}else if(mic&&(p.getBoolean("voice_conversation_mode",false)||p.getBoolean("voice_conversation_active",false)||low.contains("live voice")||low.contains("live microphone"))){title="Conversation active";detail="Speak naturally. Say That was all to end.";}else if(mic&&low.contains("listening to your command")){title="Listening to you";detail="Say your full request, then pause.";}else if(wake&&mic){title="Listening for Hey Chat";detail="You can leave this app or lock your phone.";}else if(mic){title="Microphone ready";detail="Tap Talk to start a request.";}else{title="Microphone off";detail="Tap Talk, or turn on Background listening.";}
        String orb=orbState(title);orbLive=orb.equals("listening")||orb.equals("conversation");talk.state(orb);talk.level(AppUi.level(this),orbLive&&mic);AppUi.update(voiceStatus,title);AppUi.update(voiceDetail,detail);starting.setVisibility(loading?View.VISIBLE:View.GONE);resumeListening.setVisibility(wake&&!mic&&!loading?View.VISIBLE:View.GONE);stopMicrophone.setVisibility(mic||loading?View.VISIBLE:View.GONE);meter.value(AppUi.level(this),mic);AppUi.update(connection,paired()?(VoiceOutbox.networkReady(this)?"Online":"Offline"):"Connect phone");changing=true;background.setChecked(test?p.getBoolean("ui_test_background_desired",false):wake);changing=false;testCard.setVisibility(test?View.VISIBLE:View.GONE);testButton.setText(test?"Finish test":"Test wake");long wakes=AppUi.number(this,"voice_wake_count")-AppUi.number(this,"ui_test_wake_baseline");AppUi.update(testCount,wakes>0?"Heard Hey Chat "+wakes+" time"+(wakes==1?"":"s"):"Waiting for a wake...");String heard=p.getString("voice_last_partial","");AppUi.update(partial,heard.isEmpty()?"No words detected yet.":"Heard: "+heard);String words=p.getString("voice_user_text",p.getString("voice_transcript","")),result=p.getString("voice_reply","");if(result.isEmpty())try{result=new JSONObject(p.getString("voice_last","{}")).optString("reply","");}catch(Exception ignored){}AppUi.update(voiceTranscript,words.isEmpty()?"Your words will appear here.":words);AppUi.update(answer,result.isEmpty()?"Your response will appear here.":result);if(chat!=null)chat.render(id->NativeTaskScreens.detail(this,"agent",id));conversationButton.setText(p.getBoolean("voice_conversation_mode",false)?"End conversation":"Start conversation");
        String host=Uri.parse(p.getString("origin","")).getHost();AppUi.update(accountStatus,paired()?(host==null?"Phone connected":"Connected to "+host):p.getString("status","").startsWith("Disconnected.")?"Connection expired. Pair again; saved changes stay on this phone.":"Connect this phone to your assistant server.");pairBox.setVisibility(paired()?View.GONE:View.VISIBLE);AppUi.update((TextView)getWindow().getDecorView().findViewWithTag("push_status"),p.getString("push_status","Notification connection will be set up after pairing."));AppUi.update(updateStatus,updateBusy?"Checking for updates...":p.getString("update_status","Updates arrive through release notifications."));install.setVisibility(p.contains("update_release")?View.VISIBLE:View.GONE);boolean permission=checkSelfPermission("android.permission.RECORD_AUDIO")==PackageManager.PERMISSION_GRANTED,role=false;if(Build.VERSION.SDK_INT>=29){RoleManager manager=getSystemService(RoleManager.class);role=manager!=null&&manager.isRoleHeld(RoleManager.ROLE_ASSISTANT);}AppUi.update(setupStatus,(permission?"Microphone allowed":"Microphone permission needed")+" / "+(role?"Digital assistant selected":"Select the Digital assistant"));if(selected==1)renderList();if(selected==2)renderHistory();if(resumed&&!pairBusy){Updates.prompt(this);notificationPermission();}}
    private static String orbState(String title){if(title.equals("Listening to you"))return "listening";if(title.equals("Conversation active"))return "conversation";if(title.equals("Needs attention"))return "attention";if(title.equals("Saved offline")||title.equals("Listening offline")||title.equals("Offline"))return "offline";if(title.equals("Getting ready...")||title.equals("Connecting..."))return "working";return "idle";}
    private boolean conversation(){if(!AppUi.micActive(this))return false;if(Cloud.prefs(this).getBoolean("voice_conversation_active",false))return true;String value=Cloud.prefs(this).getString("voice_status","").toLowerCase(Locale.ROOT);return value.contains("live voice")||value.contains("live microphone")||value.contains("listening to your command")||value.contains("sending voice");}
    private void setBackground(boolean on){SharedPreferences p=Cloud.prefs(this);if(p.getBoolean("voice_listening_test",false)){p.edit().putBoolean("ui_test_background_desired",on).apply();show();return;}p.edit().putBoolean("wake_enabled",on).apply();if(on)startVoice(false);else if(!conversation())stopService(new Intent(this,VoiceService.class));show();}
    private void stopMic(){Cloud.prefs(this).edit().putBoolean("wake_enabled",false).putBoolean("voice_listening_test",false).putBoolean("ui_test_background_desired",false).apply();stopService(new Intent(this,VoiceService.class));show();}
    private void toggleTest(){SharedPreferences p=Cloud.prefs(this);if(p.getBoolean("voice_listening_test",false)){finishTest();return;}p.edit().putBoolean("ui_test_background_desired",p.getBoolean("wake_enabled",false)).putLong("ui_test_wake_baseline",AppUi.number(this,"voice_wake_count")).putBoolean("voice_listening_test",true).putBoolean("wake_enabled",true).apply();stopService(new Intent(this,VoiceService.class));handler.postDelayed(()->{if(!isDestroyed()&&Cloud.prefs(this).getBoolean("voice_listening_test",false))startVoice(false);},300);show();}
    private void finishTest(){SharedPreferences p=Cloud.prefs(this);boolean desired=p.getBoolean("ui_test_background_desired",false);p.edit().putBoolean("voice_listening_test",false).putBoolean("wake_enabled",desired).apply();if(!desired)stopService(new Intent(this,VoiceService.class));show();}
    void startVoice(boolean talk){if(checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestMic(talk);return;}try{if(!AppUi.micActive(this))Cloud.prefs(this).edit().putString("voice_status","Starting microphone...").apply();startForegroundService(new Intent(this,VoiceService.class).setAction(talk?VoiceService.TALK:""));show();}catch(Exception error){Cloud.prefs(this).edit().putString("voice_status","Microphone could not start. Reopen the app and try again.").apply();show();}}
    private void requestMic(boolean talk){Cloud.prefs(this).edit().putBoolean("voice_pending_talk",talk).apply();if(checkSelfPermission("android.permission.RECORD_AUDIO")==PackageManager.PERMISSION_GRANTED){show();return;}requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},302);}
    private void chooseAssistant(){if(Build.VERSION.SDK_INT>=29){RoleManager roles=getSystemService(RoleManager.class);if(roles!=null&&roles.isRoleAvailable(RoleManager.ROLE_ASSISTANT)&&!roles.isRoleHeld(RoleManager.ROLE_ASSISTANT)){startActivityForResult(roles.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT),303);return;}}openSettings(new Intent(Settings.ACTION_VOICE_INPUT_SETTINGS));}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==Updates.INSTALL_PERMISSION)Updates.continueInstall(this);if(request==303&&result!=RESULT_OK)openSettings(new Intent(Settings.ACTION_VOICE_INPUT_SETTINGS));show();}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==302&&grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)startVoice(Cloud.prefs(this).getBoolean("voice_pending_talk",true));else if(request==302)Cloud.prefs(this).edit().putBoolean("wake_enabled",false).putBoolean("voice_listening_test",false).putString("voice_status","Microphone permission needed. Allow it in app settings.").apply();show();}
    private void openSettings(Intent intent){try{startActivity(intent);}catch(Exception error){try{startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}catch(Exception ignored){Toast.makeText(this,"Open this app's settings on your phone",Toast.LENGTH_LONG).show();}}}
    private void addMicrophoneTile(){if(Build.VERSION.SDK_INT>=33){try{getSystemService(android.app.StatusBarManager.class).requestAddTileService(new ComponentName(this,"com.personalassistant.companion.MicrophoneTile"),"Assistant microphone",android.graphics.drawable.Icon.createWithResource(this,android.R.drawable.ic_btn_speak_now),getMainExecutor(),result->Toast.makeText(this,"You can manage the tile in Quick Settings",Toast.LENGTH_SHORT).show());return;}catch(Exception ignored){}}new AlertDialog.Builder(this).setTitle("Microphone tile").setMessage("Swipe down twice, edit Quick Settings, and add Assistant microphone.").setPositiveButton("Close",null).show();}
    private void sensitivity(){String value=Cloud.prefs(this).getString("wake_sensitivity","balanced");new AlertDialog.Builder(this).setTitle("Wake sensitivity").setSingleChoiceItems(new String[]{"Balanced - fewer accidental wakes","Sensitive - amplify quiet wake input"},value.equals("sensitive")?1:0,(d,which)->{Cloud.prefs(this).edit().putString("wake_sensitivity",which==1?"sensitive":"balanced").apply();d.dismiss();}).setNegativeButton("Close",null).show();}
    private void appearance(){String value=Cloud.prefs(this).getString("ui_theme","system");new AlertDialog.Builder(this).setTitle("Appearance").setSingleChoiceItems(new String[]{"System","Light","Dark"},value.equals("light")?1:value.equals("dark")?2:0,(d,which)->{Cloud.prefs(this).edit().putString("ui_theme",new String[]{"system","light","dark"}[which]).apply();d.dismiss();recreate();}).setNegativeButton("Close",null).show();}
    private void pair(){if(pairBusy)return;final String base,pairing=code.getText().toString().trim();try{base=Cloud.origin(server.getText().toString());if(pairing.isEmpty())throw new Exception("Enter the one-use pairing code.");}catch(Exception error){AppUi.update(pairStatus,error.getMessage());return;}pairBusy=true;connect.setEnabled(false);connect.setText("Connecting...");pairProgress.setVisibility(View.VISIBLE);AppUi.update(pairStatus,"Connecting this phone...");Cloud.prefs(this).edit().putString("origin",base).apply();new Thread(()->{try{JSONObject result=(JSONObject)Cloud.call(this,"exchange",new JSONObject().put("code",pairing).put("name",Build.MODEL),false);PushRegistration.clearLocal(this);Cloud.prefs(this).edit().putBoolean("push_signing_out",false).putString("token",result.getString("token")).putString("phone_id",result.getString("id")).putString("status","Connected").commit();SyncJob.schedule(this,true);PushRegistration.start(this);TaskSyncJob.schedule(this,true);TaskSyncJob.schedule(this,false);safe(()->{pairBusy=false;connect.setEnabled(true);connect.setText("Connect phone");pairProgress.setVisibility(View.GONE);code.setText("");select(0);sync();});}catch(Exception error){safe(()->{pairBusy=false;connect.setEnabled(true);connect.setText("Connect phone");pairProgress.setVisibility(View.GONE);String message=error.getMessage()==null?"":error.getMessage();AppUi.update(pairStatus,message.contains("(400)")||message.contains("(404)")||message.contains("(410)")||message.contains("(403)")?"That code expired or was used. Get a new code and try again.":"Could not connect. Check the address and internet connection, then try again.");});}},"phone-pairing").start();}
    private void disconnect(){if(pairBusy)return;new AlertDialog.Builder(this).setTitle("Disconnect this phone?").setMessage("Your cached list and saved changes stay here. Reconnect to send them.").setPositiveButton("Disconnect",(d,w)->{stopMic();pairBusy=true;connect.setEnabled(false);Cloud.prefs(this).edit().putBoolean("push_signing_out",true).apply();android.app.job.JobScheduler jobs=getSystemService(android.app.job.JobScheduler.class);jobs.cancel(218);jobs.cancel(219);AppUi.update(accountStatus,"Disconnecting notifications...");new Thread(()->{boolean remote=true;try{PushRegistration.unregister(this);}catch(Exception error){remote=false;}Cloud.prefs(this).edit().remove("token").remove("phone_id").putString("status","Disconnected.").commit();ShoppingWidget.update(this);final boolean removed=remote;safe(()->{pairBusy=false;connect.setEnabled(true);select(3);if(!removed)Toast.makeText(this,"Phone disconnected. Notification removal could not be confirmed online.",Toast.LENGTH_LONG).show();});},"phone-disconnect").start();}).setNegativeButton("Cancel",null).show();}
    private void addItem(){if(!paired()){select(3);return;}String value=input.getText().toString().trim();if(value.isEmpty())return;try{Cloud.enqueue(this,new JSONObject().put("operation","add").put("items",new JSONArray().put(new JSONObject().put("name",value).put("quantity",""))));input.setText("");renderList();sync();}catch(Exception error){AppUi.update(status,error.getMessage());}}
    private void renderList(){if(listRows==null)return;SharedPreferences saved=Cloud.prefs(this);String key=saved.getString("snapshot","")+saved.getString("outbox","")+saved.getString("status","")+syncBusy+paired();if(key.equals(listKey))return;listKey=key;listRows.removeAllViews();listRows.setBackground(null);listRows.setPadding(0,0,0,0);AppUi.update(status,syncBusy?"Syncing...":saved.getString("status",paired()?"Cloud list":"Connect your phone to use the list"));try{JSONArray rows=Cloud.pendingList(this).optJSONArray("items");int count=0;if(rows!=null)for(int i=0;i<rows.length();i++){JSONObject item=rows.getJSONObject(i);if(item.optInt("complete")!=0)continue;count++;LinearLayout row=ui.column();row.setPadding(ui.dp(7),ui.dp(7),ui.dp(7),ui.dp(7));CheckBox check=new CheckBox(this);check.setText((item.optString("quantity")+" "+item.getString("name")).trim());check.setTextSize(16);check.setMinHeight(ui.dp(44));check.setTextColor(ui.text);check.setButtonTintList(android.content.res.ColorStateList.valueOf(ui.accent));boolean pending=item.optBoolean("pending",false)&&item.optInt("version")==0;check.setEnabled(!pending);check.setOnCheckedChangeListener((button,on)->{if(!on)return;try{Cloud.enqueue(this,new JSONObject().put("operation","complete").put("target",item.getString("id")).put("version",item.getInt("version")).put("complete",true));sync();}catch(Exception error){check.setChecked(false);AppUi.update(status,error.getMessage());}});row.addView(check,new LinearLayout.LayoutParams(-1,-2));if(pending){TextView note=ui.detail("Saved on phone");note.setTextSize(11);note.setPadding(ui.dp(41),0,0,ui.dp(3));row.addView(note);}listRows.addView(row);View line=new View(this);line.setBackgroundColor(ui.stroke);listRows.addView(line,new LinearLayout.LayoutParams(-1,ui.dp(1)));}if(count==0){listRows.addView(ui.empty("shopping","Nothing on the list","Add an item, or choose ingredients from a recipe."));}else{listRows.setBackground(ui.shape(ui.surface,16,ui.stroke));listRows.setPadding(ui.dp(7),ui.dp(3),ui.dp(7),ui.dp(3));listRows.removeViewAt(listRows.getChildCount()-1);}int pendingCount=Cloud.queue(this).length();if(pendingCount>0)AppUi.update(status,pendingCount+" change"+(pendingCount==1?"":"s")+" saved on this phone");}catch(Exception error){AppUi.update(status,"Could not read the list on this phone.");}}
    private void renderHistory(){if(historyRows==null)return;int pending=VoiceOutbox.pending(this);retryVoice.setVisibility(pending>0?View.VISIBLE:View.GONE);File receiptDirectory=new File(getFilesDir(),"voice-receipts");String historyError=Cloud.prefs(this).getString("voice_history_error","");String key=pending+":"+receiptDirectory.lastModified()+historyError+AppUi.number(this,"voice_chat_updated_at");if(key.equals(historyKey))return;historyKey=key;historyRows.removeAllViews();AppUi.update(historyStatus,(pending>0?pending+" voice command"+(pending==1?"":"s")+" waiting to send":"No saved commands waiting to send")+(historyError.isEmpty()?"":". Recent history could not be saved on this phone."));File[] files=receiptDirectory.listFiles((directory,name)->name.endsWith(".json"));if(files==null||files.length==0){historyRows.addView(ui.empty("activity","Nothing here yet","Your acknowledged voice requests will appear here."));return;}Arrays.sort(files,(a,b)->Long.compare(b.lastModified(),a.lastModified()));for(int i=0;i<Math.min(files.length,12);i++)try{File file=files[i];JSONObject receipt=new JSONObject(VoiceOutbox.read(file));LinearLayout row=ui.row();row.setGravity(Gravity.TOP);AppUi.TimelineMark mark=new AppUi.TimelineMark(this,ui.warm,ui.stroke);row.addView(mark,new LinearLayout.LayoutParams(ui.dp(20),-1));LinearLayout content=ui.column();content.setPadding(ui.dp(12),ui.dp(3),0,ui.dp(22));TextView time=ui.detail(DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(file.lastModified())));time.setTextSize(11);time.setTextColor(ui.warm);content.addView(time);ui.space(content,8);TextView request=ui.text(receipt.optString("text","Voice request"),17,true);request.setMaxLines(3);request.setEllipsize(android.text.TextUtils.TruncateAt.END);content.addView(request);ui.space(content,7);TextView response=ui.detail(receipt.optString("reply",receipt.optString("status","Acknowledged")));response.setMaxLines(4);response.setEllipsize(android.text.TextUtils.TruncateAt.END);content.addView(response);row.addView(content,new LinearLayout.LayoutParams(0,-2,1));row.setOnClickListener(v->{String task=receipt.optString("task_id");if(!task.isEmpty()&&(receipt.optString("status").equals("queued")||receipt.optString("status").equals("running")))NativeTaskScreens.detail(this,"agent",task);else new AlertDialog.Builder(this).setTitle("Voice request").setMessage(receipt.optString("text","")+"\n\n"+receipt.optString("reply",receipt.optString("status",""))).setPositiveButton("Close",null).show();});row.setClickable(true);row.setFocusable(true);row.setContentDescription(receipt.optString("text","Voice request"));historyRows.addView(row,new LinearLayout.LayoutParams(-1,-2));}catch(Exception ignored){}}
    private void notificationPermission(){if(!resumed||!paired()||Build.VERSION.SDK_INT<33||checkSelfPermission("android.permission.POST_NOTIFICATIONS")==PackageManager.PERMISSION_GRANTED||Cloud.prefs(this).getBoolean("notification_permission_requested",false)||Updates.promptVisible(this))return;Cloud.prefs(this).edit().putBoolean("notification_permission_requested",true).apply();requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},301);}
    private void taskHistory(){if(!paired()){select(3);return;}NativeTaskScreens.history(this);}
    private boolean openTaskIntent(Intent intent){String id=intent.getStringExtra("task_id");if(id==null||id.isEmpty())return false;select(2);handler.post(()->NativeTaskScreens.detail(this,intent.getStringExtra("task_kind")==null?"agent":intent.getStringExtra("task_kind"),id));intent.removeExtra("task_id");return true;}
    private void toggleConversation(){if(!paired()){select(3);return;}boolean active=Cloud.prefs(this).getBoolean("voice_conversation_mode",false);if(checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestMic(false);return;}if(Cloud.prefs(this).getBoolean("voice_listening_test",false))finishTest();startForegroundService(new Intent(this,VoiceService.class).setAction(active?VoiceService.END_CONVERSATION:VoiceService.START_CONVERSATION));show();}
    private void openWeb(String path){if(!paired()){select(3);return;}try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Cloud.prefs(this).getString("origin","")+path)));}catch(Exception error){Toast.makeText(this,"No browser is available",Toast.LENGTH_LONG).show();}}
    void review(){
        if(syncBusy){Toast.makeText(this,"Sync is already running",Toast.LENGTH_SHORT).show();return;}
        try{JSONArray queue=Cloud.queue(this);if(queue.length()==0){Toast.makeText(this,"No saved shopping changes",Toast.LENGTH_SHORT).show();return;}JSONObject first=queue.getJSONObject(0);String operation=first.optString("operation"),description=operation.equals("add")?"Add items to the shopping list":operation.equals("recipe_save")?"Save a recipe":"Update a shopping item";
            new AlertDialog.Builder(this).setTitle("Saved changes").setMessage(queue.length()+" change"+(queue.length()==1?"":"s")+" waiting.\n\nNext: "+description).setPositiveButton("Try again",(d,w)->{
                if(!operation.equals("complete")){sync();return;}
                SyncJob.executor.execute(()->{try{JSONObject latest=(JSONObject)Cloud.call(this,"list",null,true);JSONArray items=latest.getJSONArray("items");for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);if(item.getString("id").equals(first.optString("target"))){Cloud.rebaseQueuedCompletion(this,first.getString("id"),item.getInt("version"));break;}}safe(this::sync);}catch(Exception error){safe(()->AppUi.update(status,error.getMessage()));}});
            }).setNegativeButton("Keep on phone",null).show();
        }catch(Exception error){AppUi.update(status,error.getMessage());}
    }
    void checkUpdates(boolean force){if(updateBusy)return;updateBusy=true;show();SyncJob.executor.execute(()->{try{Updates.check(this,force);}catch(Exception error){Cloud.prefs(this).edit().putString("update_status","Update check unavailable. Try again later.").apply();}safe(()->{updateBusy=false;show();});});}
    void sync(){if(!paired()||syncBusy)return;syncBusy=true;renderList();SyncJob.executor.execute(()->{try{Cloud.sync(this);safe(()->{syncBusy=false;renderList();show();alarms();});}catch(Exception error){Cloud.prefs(this).edit().putString("status",error.getMessage()).apply();ShoppingWidget.update(this);safe(()->{syncBusy=false;renderList();show();});}});}
    void alarms(){SyncJob.executor.execute(()->{try{JSONArray actions=(JSONArray)Cloud.call(this,"actions",null,true);for(int n=0;n<actions.length();n++){
        JSONObject a=actions.getJSONObject(n),body=a.getJSONObject("body");String id=a.getString("id");
        if(!"alarm".equals(body.optString("type")))continue;
        safe(()->handoff(id,body));
    }}catch(Exception e){safe(()->status.setText(e.getMessage()));}});}
    void handoff(String id,JSONObject body){
        String prior=Cloud.prefs(this).getString("alarm:"+id,"");
        if(!prior.isEmpty()){receipt(id,"delegated".equals(prior)?"delegated":"failed");return;}
        try{
            Intent clock=new Intent(AlarmClock.ACTION_SET_ALARM).putExtra(AlarmClock.EXTRA_HOUR,body.getInt("hour")).putExtra(AlarmClock.EXTRA_MINUTES,body.getInt("minute")).putExtra(AlarmClock.EXTRA_MESSAGE,body.getString("label")).putExtra(AlarmClock.EXTRA_SKIP_UI,true);
            if(clock.resolveActivity(getPackageManager())==null)throw new Exception("No compatible Clock app found");
            Cloud.prefs(this).edit().putString("alarm:"+id,"starting").commit();startActivity(clock);
            Cloud.prefs(this).edit().putString("alarm:"+id,"delegated").commit();receipt(id,"delegated");status.setText("Alarm handed to Clock. Verify it there on the first test.");
        }catch(Exception e){Cloud.prefs(this).edit().putString("alarm:"+id,"failed").commit();receipt(id,"failed");status.setText(e.getMessage());}
    }
    void receipt(String id,String state){SyncJob.executor.execute(()->{try{Cloud.call(this,"actions/"+id+"/receipt",new JSONObject().put("state",state),true);}catch(Exception e){safe(()->status.setText("Alarm receipt pending. Check Clock; reconnect to report the result."));}});}
    void share(String value){
        if(value==null||value.trim().isEmpty())return;
        if(Cloud.prefs(this).getString("token","").isEmpty()){status.setText("Pair the companion, then share the recipe again.");return;}
        SyncJob.executor.execute(()->{try{
            JSONObject result=(JSONObject)Cloud.call(this,"recipes/import/preview",new JSONObject().put("content",value),true);
            JSONArray recipes=result.getJSONArray("recipes");StringBuilder preview=new StringBuilder();
            for(int n=0;n<recipes.length();n++){JSONObject recipe=recipes.getJSONObject(n);preview.append(recipe.getString("title")).append("\n");JSONArray rows=recipe.getJSONArray("ingredients");for(int i=0;i<rows.length();i++){JSONObject item=rows.getJSONObject(i);preview.append(item.optString("quantity")).append(" ").append(item.getString("name")).append("\n");}preview.append("\n");}
            safe(()->new AlertDialog.Builder(this).setTitle("Import recipes").setMessage(preview.toString()).setPositiveButton("Save recipes",(d,w)->{try{
                for(int n=0;n<recipes.length();n++)Cloud.enqueue(this,new JSONObject().put("operation","recipe_save").put("recipe",recipes.getJSONObject(n)));sync();
            }catch(Exception e){status.setText(e.getMessage());}}).setNegativeButton("Cancel",null).show());
        }catch(Exception e){safe(()->status.setText("Recipe could not be parsed. Open Recipes and import to edit the shared text. "+e.getMessage()));}});
    }
}
