package com.personalassistant.companion;

import android.app.*;
import android.app.role.RoleManager;
import android.content.*;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.*;
import android.provider.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Voice-first native companion. Background updates never reconstruct an input form. */
public class MainActivity extends Activity {
    private AppUi ui;private LinearLayout body;
    private final LinearLayout[] pages=new LinearLayout[4];private AppUi.NavBar navBar;private boolean orbLive;
    private MainVoice voice;private MainShopping shopping;private MainReceipts receipts;private MainSettings settings;private boolean resumed,themePending;
    private int selected;private boolean registered,refreshQueued,pairBusy,syncBusy,updateBusy;
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final Runnable themeCheck=this::checkTheme;
    private final SharedPreferences.OnSharedPreferenceChangeListener prefsListener=(p,key)->{if("voice_level".equals(key)){if(voice!=null){voice.meter.value(AppUi.level(this),AppUi.micActive(this));voice.talk.level(AppUi.level(this),orbLive&&AppUi.micActive(this));}return;}if(!refreshQueued){refreshQueued=true;handler.postDelayed(()->{refreshQueued=false;if(!isDestroyed())show();},80);}};
    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent intent){show();if("com.personalassistant.companion.GROCERY_STATE".equals(intent.getAction()))renderList();}};
    @Override public void onCreate(Bundle saved){AppUi.theme(this);super.onCreate(saved);ui=new AppUi(this);ui.window();build();if(saved!=null){selected=saved.getInt("tab",0);shopping.input.setText(saved.getString("draft",""));settings.server.setText(saved.getString("server",settings.server.getText().toString()));settings.code.setText(saved.getString("code",""));}select(selected);if(Intent.ACTION_SEND.equals(getIntent().getAction())){select(1);share(getIntent().getStringExtra(Intent.EXTRA_TEXT));}if(paired()){sync();PushRegistration.start(this);TaskSyncJob.schedule(this,true);}checkUpdates(false);openTaskIntent(getIntent());}
    @Override public void onSaveInstanceState(Bundle state){state.putInt("tab",selected);state.putString("draft",shopping.input.getText().toString());state.putString("server",settings.server.getText().toString());state.putString("code",settings.code.getText().toString());super.onSaveInstanceState(state);}
    @Override public void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(Intent.ACTION_SEND.equals(intent.getAction())){select(1);share(intent.getStringExtra(Intent.EXTRA_TEXT));}else if(!openTaskIntent(intent))select(0);if(paired())sync();}
    @Override public void onStart(){super.onStart();IntentFilter filter=new IntentFilter("com.personalassistant.companion.VOICE_STATE");filter.addAction("com.personalassistant.companion.GROCERY_STATE");filter.addAction("com.personalassistant.companion.TASK_STATE");if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,filter);registered=true;Cloud.prefs(this).registerOnSharedPreferenceChangeListener(prefsListener);show();}
    @Override public void onResume(){super.onResume();resumed=true;if(ui!=null){ui.window();show();settings.refreshNow(paired());checkUpdates(false);if(paired())TaskSyncJob.schedule(this,false);checkTheme();}}
    @Override public void onPause(){resumed=false;handler.removeCallbacks(themeCheck);if(shopping!=null)shopping.commit(false);super.onPause();}
    @Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(focus&&ui!=null){ui.window();if(themePending)checkTheme();}}
    @Override public void onBackPressed(){if(selected!=0){select(0);return;}super.onBackPressed();}
    @Override public void onDestroy(){NativeTaskScreens.close(this);Updates.dismissPrompt(this);super.onDestroy();}
    @Override public void onStop(){if(shopping!=null)shopping.commit(false);if(registered){unregisterReceiver(receiver);registered=false;}Cloud.prefs(this).unregisterOnSharedPreferenceChangeListener(prefsListener);super.onStop();}
    boolean paired(){SharedPreferences p=Cloud.prefs(this);return !p.getString("token","").isEmpty()&&!p.getString("status","").startsWith("Disconnected.");}
    boolean syncing(){return syncBusy;}
    boolean updating(){return updateBusy;}
    private void safe(Runnable action){runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())action.run();});}
    void note(String message){if(shopping!=null)shopping.note(message,"warning","alert");}

    /** With "Sunrise & sunset" the open screen flips theme at the computed moment; a dialog or sheet in front delays it until focus returns. */
    private void checkTheme(){
        handler.removeCallbacks(themeCheck);if(ui==null||isFinishing()||isDestroyed())return;
        if(AppUi.dark(this)!=ui.dark){if(hasWindowFocus()){themePending=false;recreate();}else themePending=true;return;}
        themePending=false;if(!resumed||!"sun".equals(Cloud.prefs(this).getString("ui_theme","sun")))return;
        long now=System.currentTimeMillis();handler.postDelayed(themeCheck,Math.max(1000,DaylightTheme.nextChange(now)-now+1000));
    }

    private void build(){
        LinearLayout root=ui.column();root.setFitsSystemWindows(true);root.setBackground(ui.backgroundDrawable());body=ui.column();FrameLayout stage=new FrameLayout(this);stage.addView(body,new FrameLayout.LayoutParams(-1,-1));View fade=new View(this);fade.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);fade.setBackground(new android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.TOP_BOTTOM,new int[]{AppUi.alpha(ui.background,0f),ui.background}));stage.addView(fade,new FrameLayout.LayoutParams(-1,ui.dp(28),Gravity.BOTTOM));root.addView(stage,new LinearLayout.LayoutParams(-1,0,1));
        for(int i=0;i<4;i++){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);pages[i]=ui.column();pages[i].setPadding(ui.dp(20),ui.dp(i==0?10:20),ui.dp(20),ui.dp(24));scroll.addView(pages[i]);body.addView(scroll,new LinearLayout.LayoutParams(-1,-1));}
        voice=new MainVoice(this,ui,pages[0]);shopping=new MainShopping(this,ui,pages[1]);receipts=new MainReceipts(this,ui,pages[2]);settings=new MainSettings(this,ui,pages[3]);
        navBar=ui.navBar(new String[]{"Voice","Shopping","Activity","Settings"},new String[]{"voice","shopping","activity","settings"},new String[]{"nav_voice","nav_shopping","nav_activity","nav_settings"},this::select);root.addView(navBar,navBar.params());setContentView(root);
    }
    void select(int index){int previous=selected;selected=index;for(int i=0;i<4;i++){boolean entering=i==index&&body.getChildAt(i).getVisibility()!=View.VISIBLE;body.getChildAt(i).setVisibility(i==index?View.VISIBLE:View.GONE);if(entering)AppUi.slide(body.getChildAt(i),index>previous?1:-1);}navBar.select(index,true);if(index==1)renderList();if(index==2)receipts.render();show();}
    void openConnection(){select(3);if(!paired())settings.code.requestFocus();}
    void needPairing(){Toast.makeText(this,"Connect your phone first",Toast.LENGTH_SHORT).show();select(3);}
    void talkTapped(){if(!paired()){openConnection();Toast.makeText(this,"Connect your phone first",Toast.LENGTH_SHORT).show();return;}if(Cloud.prefs(this).getBoolean("voice_listening_test",false))finishTest();startVoice(true);}

    void show(){if(ui==null||voice==null)return;SharedPreferences p=Cloud.prefs(this);boolean mic=AppUi.micActive(this),test=p.getBoolean("voice_listening_test",false),wake=p.getBoolean("wake_enabled",false);String raw=p.getString("voice_status","Microphone off"),low=raw.toLowerCase(Locale.ROOT);boolean loading=low.contains("starting")||low.contains("preparing")||low.contains("loading");String title,detail;
        if(wake&&!mic&&!loading){title=test?"Wake test paused":"Listening paused";detail="Background listening is enabled, but the microphone is off. Resume to restart it.";}else if(test){title=loading?"Getting ready...":"Wake test";detail="Local only. Say Hey Chat at your normal volume.";}else if(loading){title="Getting ready...";detail="The microphone and wake model are starting.";}else if(low.contains("sending")||low.contains("connecting live")){title="Connecting...";detail="Your audio is buffered while the connection starts.";}else if(low.contains("no internet")||low.contains("saved on this phone")||low.contains("cloud unavailable")){title=VoiceOutbox.pending(this)>0?"Saved offline":wake&&mic?"Listening offline":"Offline";detail=raw;}else if(low.contains("permission")||low.contains("interrupted")||low.contains("could not")||low.contains("unavailable")||low.contains("voice stopped")||low.contains("connection lost")){title="Needs attention";detail=raw;}else if(mic&&(p.getBoolean("voice_conversation_mode",false)||p.getBoolean("voice_conversation_active",false)||low.contains("live voice")||low.contains("live microphone"))){title="Conversation active";detail="Speak naturally. Say That was all to end.";}else if(mic&&low.contains("listening to your command")){title="Listening to you";detail="Say your full request, then pause.";}else if(wake&&mic){title="Listening for Hey Chat";detail="You can leave this app or lock your phone.";}else if(mic){title="Microphone ready";detail="Tap Talk to start a request.";}else{title="Microphone off";detail="Tap Talk, or turn on Background listening.";}
        String orb=orbState(title);orbLive=orb.equals("listening")||orb.equals("conversation");voice.update(title,detail,orb,loading,mic,test,wake,paired(),p.getBoolean("voice_conversation_mode",false));
        settings.refresh(selected==3,paired());if(selected==1)renderList();if(selected==2)receipts.render();if(resumed&&!pairBusy){Updates.prompt(this);notificationPermission();}}
    private static String orbState(String title){if(title.equals("Listening to you"))return "listening";if(title.equals("Conversation active"))return "conversation";if(title.equals("Needs attention"))return "attention";if(title.equals("Saved offline")||title.equals("Listening offline")||title.equals("Offline"))return "offline";if(title.equals("Getting ready...")||title.equals("Connecting..."))return "working";return "idle";}
    private boolean conversation(){if(!AppUi.micActive(this))return false;if(Cloud.prefs(this).getBoolean("voice_conversation_active",false))return true;String value=Cloud.prefs(this).getString("voice_status","").toLowerCase(Locale.ROOT);return value.contains("live voice")||value.contains("live microphone")||value.contains("listening to your command")||value.contains("sending voice");}
    void setBackground(boolean on){SharedPreferences p=Cloud.prefs(this);if(p.getBoolean("voice_listening_test",false)){p.edit().putBoolean("ui_test_background_desired",on).apply();show();return;}p.edit().putBoolean("wake_enabled",on).apply();if(on)startVoice(false);else if(!conversation())stopService(new Intent(this,VoiceService.class));show();}
    void stopMic(){Cloud.prefs(this).edit().putBoolean("wake_enabled",false).putBoolean("voice_listening_test",false).putBoolean("ui_test_background_desired",false).apply();stopService(new Intent(this,VoiceService.class));show();}
    void toggleTest(){SharedPreferences p=Cloud.prefs(this);if(p.getBoolean("voice_listening_test",false)){finishTest();return;}p.edit().putBoolean("ui_test_background_desired",p.getBoolean("wake_enabled",false)).putLong("ui_test_wake_baseline",AppUi.number(this,"voice_wake_count")).putBoolean("voice_listening_test",true).putBoolean("wake_enabled",true).apply();stopService(new Intent(this,VoiceService.class));handler.postDelayed(()->{if(!isDestroyed()&&Cloud.prefs(this).getBoolean("voice_listening_test",false))startVoice(false);},300);show();}
    private void finishTest(){SharedPreferences p=Cloud.prefs(this);boolean desired=p.getBoolean("ui_test_background_desired",false);p.edit().putBoolean("voice_listening_test",false).putBoolean("wake_enabled",desired).apply();if(!desired)stopService(new Intent(this,VoiceService.class));show();}
    void startVoice(boolean talk){if(checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestMic(talk);return;}try{if(!AppUi.micActive(this))Cloud.prefs(this).edit().putString("voice_status","Starting microphone...").apply();startForegroundService(new Intent(this,VoiceService.class).setAction(talk?VoiceService.TALK:""));show();}catch(Exception error){Cloud.prefs(this).edit().putString("voice_status","Microphone could not start. Reopen the app and try again.").apply();show();}}
    private void requestMic(boolean talk){Cloud.prefs(this).edit().putBoolean("voice_pending_talk",talk).putBoolean("mic_requested",true).apply();if(checkSelfPermission("android.permission.RECORD_AUDIO")==PackageManager.PERMISSION_GRANTED){show();return;}requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},302);}
    /** Once the system stops showing its dialog (denied for good), the row leads to the app's own permission settings. */
    void microphonePermission(){
        if(checkSelfPermission("android.permission.RECORD_AUDIO")==PackageManager.PERMISSION_GRANTED){Toast.makeText(this,"Microphone is allowed",Toast.LENGTH_SHORT).show();return;}
        if(Cloud.prefs(this).getBoolean("mic_requested",false)&&!shouldShowRequestPermissionRationale("android.permission.RECORD_AUDIO")){Toast.makeText(this,"Allow the microphone in this app's settings",Toast.LENGTH_LONG).show();openSettings(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));return;}
        requestMic(false);
    }
    void chooseAssistant(){if(Build.VERSION.SDK_INT>=29){RoleManager roles=getSystemService(RoleManager.class);if(roles!=null&&roles.isRoleAvailable(RoleManager.ROLE_ASSISTANT)&&!roles.isRoleHeld(RoleManager.ROLE_ASSISTANT)){startActivityForResult(roles.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT),303);return;}}openSettings(new Intent(Settings.ACTION_VOICE_INPUT_SETTINGS));}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==Updates.INSTALL_PERMISSION)Updates.continueInstall(this);if(request==303&&result!=RESULT_OK)openSettings(new Intent(Settings.ACTION_VOICE_INPUT_SETTINGS));show();}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==302&&grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)startVoice(Cloud.prefs(this).getBoolean("voice_pending_talk",true));else if(request==302){Cloud.prefs(this).edit().putBoolean("wake_enabled",false).putBoolean("voice_listening_test",false).putString("voice_status","Microphone permission needed. Allow it in app settings.").apply();}show();}
    void openSettings(Intent intent){try{startActivity(intent);}catch(Exception error){try{startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}catch(Exception ignored){Toast.makeText(this,"Open this app's settings on your phone",Toast.LENGTH_LONG).show();}}}
    void notificationSettings(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},301);else openSettings(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));}
    void addMicrophoneTile(){if(Build.VERSION.SDK_INT>=33){try{getSystemService(android.app.StatusBarManager.class).requestAddTileService(new ComponentName(this,"com.personalassistant.companion.MicrophoneTile"),"Assistant microphone",android.graphics.drawable.Icon.createWithResource(this,android.R.drawable.ic_btn_speak_now),getMainExecutor(),result->Toast.makeText(this,"You can manage the tile in Quick Settings",Toast.LENGTH_SHORT).show());return;}catch(Exception ignored){}}new AlertDialog.Builder(this).setTitle("Microphone tile").setMessage("Swipe down twice, edit Quick Settings, and add Assistant microphone.").setPositiveButton("Close",null).show();}
    void sensitivity(){String value=Cloud.prefs(this).getString("wake_sensitivity","balanced");new AlertDialog.Builder(this).setTitle("Wake sensitivity").setSingleChoiceItems(new String[]{"Balanced - fewer accidental wakes","Sensitive - amplify quiet wake input"},value.equals("sensitive")?1:0,(d,which)->{Cloud.prefs(this).edit().putString("wake_sensitivity",which==1?"sensitive":"balanced").apply();d.dismiss();}).setNegativeButton("Close",null).show();}
    void appearance(){String value=Cloud.prefs(this).getString("ui_theme","sun");String[] modes={"sun","system","light","dark"};int current=Math.max(0,Arrays.asList(modes).indexOf(value));new AlertDialog.Builder(this).setTitle("Appearance").setSingleChoiceItems(new String[]{"Sunrise & sunset","System","Light","Dark"},current,(d,which)->{d.dismiss();if(modes[which].equals(value))return;Cloud.prefs(this).edit().putString("ui_theme",modes[which]).apply();recreate();}).setNegativeButton("Close",null).show();}
    void pair(){if(pairBusy)return;final String base,pairing=settings.code.getText().toString().trim();try{base=Cloud.origin(settings.server.getText().toString());if(pairing.isEmpty())throw new Exception("Enter the one-use pairing code.");}catch(Exception error){settings.pairNote(error.getMessage());return;}pairBusy=true;settings.pairing(true);settings.pairNote("Connecting this phone...");Cloud.prefs(this).edit().putString("origin",base).apply();new Thread(()->{try{JSONObject result=(JSONObject)Cloud.call(this,"exchange",new JSONObject().put("code",pairing).put("name",Build.MODEL),false);PushRegistration.clearLocal(this);Cloud.prefs(this).edit().putBoolean("push_signing_out",false).putString("token",result.getString("token")).putString("phone_id",result.getString("id")).putString("status","Connected").commit();SyncJob.schedule(this,true);PushRegistration.start(this);TaskSyncJob.schedule(this,true);TaskSyncJob.schedule(this,false);safe(()->{pairBusy=false;settings.pairing(false);settings.code.setText("");select(0);sync();});}catch(Exception error){safe(()->{pairBusy=false;settings.pairing(false);String message=error.getMessage()==null?"":error.getMessage();settings.pairNote(message.contains("(400)")||message.contains("(404)")||message.contains("(410)")||message.contains("(403)")?"That code expired or was used. Get a new code and try again.":"Could not connect. Check the address and internet connection, then try again.");});}},"phone-pairing").start();}
    void disconnect(){if(pairBusy)return;new AlertDialog.Builder(this).setTitle("Disconnect this phone?").setMessage("Your cached list and saved changes stay here. Reconnect to send them.").setPositiveButton("Disconnect",(d,w)->{stopMic();pairBusy=true;settings.connect.setEnabled(false);Cloud.prefs(this).edit().putBoolean("push_signing_out",true).apply();android.app.job.JobScheduler jobs=getSystemService(android.app.job.JobScheduler.class);jobs.cancel(218);jobs.cancel(219);AppUi.update(settings.accountStatus,"Disconnecting notifications...");new Thread(()->{boolean remote=true;try{PushRegistration.unregister(this);}catch(Exception error){remote=false;}Cloud.prefs(this).edit().remove("token").remove("phone_id").putString("status","Disconnected.").commit();ShoppingWidget.update(this);final boolean removed=remote;safe(()->{pairBusy=false;settings.connect.setEnabled(true);select(3);if(!removed)Toast.makeText(this,"Phone disconnected. Notification removal could not be confirmed online.",Toast.LENGTH_LONG).show();});},"phone-disconnect").start();}).setNegativeButton("Cancel",null).show();}
    void renderList(){if(shopping!=null)shopping.render();}
    private void notificationPermission(){if(!resumed||!paired()||Build.VERSION.SDK_INT<33||checkSelfPermission("android.permission.POST_NOTIFICATIONS")==PackageManager.PERMISSION_GRANTED||Cloud.prefs(this).getBoolean("notification_permission_requested",false)||Updates.promptVisible(this))return;Cloud.prefs(this).edit().putBoolean("notification_permission_requested",true).apply();requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},301);}
    void taskHistory(){if(!paired()){needPairing();return;}NativeTaskScreens.history(this);}
    void openTask(String id){NativeTaskScreens.detail(this,"agent",id);}
    private boolean openTaskIntent(Intent intent){String id=intent.getStringExtra("task_id");if(id==null||id.isEmpty())return false;select(2);handler.post(()->NativeTaskScreens.detail(this,intent.getStringExtra("task_kind")==null?"agent":intent.getStringExtra("task_kind"),id));intent.removeExtra("task_id");return true;}
    void toggleConversation(){if(!paired()){needPairing();return;}boolean active=Cloud.prefs(this).getBoolean("voice_conversation_mode",false);if(checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED){requestMic(false);return;}if(Cloud.prefs(this).getBoolean("voice_listening_test",false))finishTest();startForegroundService(new Intent(this,VoiceService.class).setAction(active?VoiceService.END_CONVERSATION:VoiceService.START_CONVERSATION));show();}
    void openWeb(String path){if(!paired()){needPairing();return;}try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Cloud.prefs(this).getString("origin","")+path)));}catch(Exception error){Toast.makeText(this,"No browser is available",Toast.LENGTH_LONG).show();}}
    void recipes(){RecipeLibrary.show(this,this::sync,this::share,()->openWeb("/groceries/"));}
    void review(){
        if(syncBusy){Toast.makeText(this,"Sync is already running",Toast.LENGTH_SHORT).show();return;}
        try{JSONArray queue=Cloud.queue(this);if(queue.length()==0){Toast.makeText(this,"No saved shopping changes",Toast.LENGTH_SHORT).show();return;}JSONObject first=queue.getJSONObject(0);String operation=first.optString("operation"),description=operation.equals("add")?"Add items to the shopping list":operation.equals("recipe_save")?"Save a recipe":"Update a shopping item";
            new AlertDialog.Builder(this).setTitle("Saved changes").setMessage(queue.length()+" change"+(queue.length()==1?"":"s")+" waiting.\n\nNext: "+description).setPositiveButton("Try again",(d,w)->{
                if(!operation.equals("complete")){sync();return;}
                SyncJob.executor.execute(()->{try{JSONObject latest=(JSONObject)Cloud.call(this,"list",null,true);JSONArray items=latest.getJSONArray("items");for(int i=0;i<items.length();i++){JSONObject item=items.getJSONObject(i);if(item.getString("id").equals(first.optString("target"))){Cloud.rebaseQueuedCompletion(this,first.getString("id"),item.getInt("version"));break;}}safe(this::sync);}catch(Exception error){safe(()->note(error.getMessage()));}});
            }).setNegativeButton("Keep on phone",null).show();
        }catch(Exception error){note(error.getMessage());}
    }
    void checkUpdates(boolean force){if(updateBusy)return;updateBusy=true;show();SyncJob.executor.execute(()->{try{Updates.check(this,force);}catch(Exception error){Cloud.prefs(this).edit().putString("update_status","Update check unavailable. Try again later.").apply();}safe(()->{updateBusy=false;show();});});}
    void sync(){if(!paired()||syncBusy)return;syncBusy=true;renderList();SyncJob.executor.execute(()->{try{Cloud.sync(this);safe(()->{syncBusy=false;renderList();show();alarms();});}catch(Exception error){Cloud.prefs(this).edit().putString("status",error.getMessage()).apply();ShoppingWidget.update(this);safe(()->{syncBusy=false;renderList();show();});}});}
    void alarms(){SyncJob.executor.execute(()->{try{JSONArray actions=(JSONArray)Cloud.call(this,"actions",null,true);for(int n=0;n<actions.length();n++){
        JSONObject a=actions.getJSONObject(n),body=a.getJSONObject("body");String id=a.getString("id");
        if(!"alarm".equals(body.optString("type")))continue;
        safe(()->handoff(id,body));
    }}catch(Exception e){safe(()->note(e.getMessage()));}});}
    void handoff(String id,JSONObject body){
        String prior=Cloud.prefs(this).getString("alarm:"+id,"");
        if(!prior.isEmpty()){receipt(id,"delegated".equals(prior)?"delegated":"failed");return;}
        try{
            Intent clock=new Intent(AlarmClock.ACTION_SET_ALARM).putExtra(AlarmClock.EXTRA_HOUR,body.getInt("hour")).putExtra(AlarmClock.EXTRA_MINUTES,body.getInt("minute")).putExtra(AlarmClock.EXTRA_MESSAGE,body.getString("label")).putExtra(AlarmClock.EXTRA_SKIP_UI,true);
            if(clock.resolveActivity(getPackageManager())==null)throw new Exception("No compatible Clock app found");
            Cloud.prefs(this).edit().putString("alarm:"+id,"starting").commit();startActivity(clock);
            Cloud.prefs(this).edit().putString("alarm:"+id,"delegated").commit();receipt(id,"delegated");shopping.note("Alarm handed to Clock. Verify it there on the first test.","info","info");
        }catch(Exception e){Cloud.prefs(this).edit().putString("alarm:"+id,"failed").commit();receipt(id,"failed");note(e.getMessage());}
    }
    void receipt(String id,String state){SyncJob.executor.execute(()->{try{Cloud.call(this,"actions/"+id+"/receipt",new JSONObject().put("state",state),true);}catch(Exception e){safe(()->note("Alarm receipt pending. Check Clock; reconnect to report the result."));}});}
    void share(String value){
        if(value==null||value.trim().isEmpty())return;
        if(Cloud.prefs(this).getString("token","").isEmpty()){note("Pair the companion, then share the recipe again.");return;}
        SyncJob.executor.execute(()->{try{
            JSONObject result=(JSONObject)Cloud.call(this,"recipes/import/preview",new JSONObject().put("content",value),true);
            JSONArray recipes=result.getJSONArray("recipes");StringBuilder preview=new StringBuilder();
            for(int n=0;n<recipes.length();n++){JSONObject recipe=recipes.getJSONObject(n);preview.append(recipe.getString("title")).append("\n");JSONArray rows=recipe.getJSONArray("ingredients");for(int i=0;i<rows.length();i++){JSONObject item=rows.getJSONObject(i);preview.append(item.optString("quantity")).append(" ").append(item.getString("name")).append("\n");}preview.append("\n");}
            safe(()->new AlertDialog.Builder(this).setTitle("Import recipes").setMessage(preview.toString()).setPositiveButton("Save recipes",(d,w)->{try{
                for(int n=0;n<recipes.length();n++)Cloud.enqueue(this,new JSONObject().put("operation","recipe_save").put("recipe",recipes.getJSONObject(n)));sync();
            }catch(Exception e){note(e.getMessage());}}).setNegativeButton("Cancel",null).show());
        }catch(Exception e){safe(()->note("Recipe could not be parsed. Open Recipes and import to edit the shared text. "+e.getMessage()));}});
    }
}
