package com.personalassistant.companion;

import android.app.*;
import android.content.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.DateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Authenticated native task history and durable same-session continuation. */
final class NativeTaskScreens {
    private static final ExecutorService network=Executors.newSingleThreadExecutor();
    private static final Map<Activity,List<Screen>> openScreens=new WeakHashMap<>();
    static void close(Activity activity){List<Screen> list=openScreens.remove(activity);if(list!=null)for(Screen screen:new ArrayList<>(list))screen.dialog.dismiss();}
    static void history(Activity a){new History(a).open();}
    static void detail(Activity a,String kind,String id){if(id!=null&&id.matches("[A-Za-z0-9_-]{1,160}"))new Detail(a,kind.equals("command")?"command":"agent",id).open();}
    static long timestamp(Object value){try{if(value instanceof Number)return ((Number)value).longValue()*1000;String raw=String.valueOf(value);return java.time.Instant.parse(raw).toEpochMilli();}catch(Exception ignored){return 0;}}
    static String state(String raw){if(raw.equals("leased")||raw.equals("running")||raw.equals("in_progress"))return "In progress";if(raw.equals("completed")||raw.equals("complete"))return "Completed";if(raw.equals("needs_input"))return "Needs your input";if(raw.equals("failed"))return "Failed";if(raw.equals("cancelled"))return "Cancelled";if(raw.equals("queued")||raw.equals("pending"))return "Queued";return raw.isEmpty()?"Received":raw.replace('_',' ');}
    private abstract static class Screen {
        final Activity a;final AppUi ui;final Dialog dialog;final LinearLayout body,root;final TextView status;final Handler main=new Handler(Looper.getMainLooper());boolean closed,registered;
        final BroadcastReceiver changes=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){changed();}};
        Screen(Activity a,String title){this.a=a;ui=new AppUi(a);dialog=new Dialog(a);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);root=ui.column();root.setFitsSystemWindows(true);root.setBackground(ui.backgroundDrawable());LinearLayout header=ui.row();header.setPadding(ui.dp(12),ui.dp(8),ui.dp(18),ui.dp(8));android.widget.ImageButton back=ui.iconButton("back","Back from "+title,dialog::dismiss);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(ui.dp(48),ui.dp(48));bp.rightMargin=ui.dp(8);header.addView(back,bp);header.addView(ui.text(title,22,true),new LinearLayout.LayoutParams(0,-2,1));root.addView(header);ScrollView scroll=new ScrollView(a);scroll.setFillViewport(true);body=ui.column();body.setPadding(ui.dp(22),ui.dp(8),ui.dp(22),ui.dp(24));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));status=ui.detail("");status.setTag("native_task_status");status.setTextSize(12);body.addView(status);ui.space(body,12);dialog.setContentView(root);dialog.setOnDismissListener(d->{closed=true;List<Screen> list=openScreens.get(a);if(list!=null){list.remove(this);if(list.isEmpty())openScreens.remove(a);}if(registered){a.unregisterReceiver(changes);registered=false;}});dialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);dialog.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}
        void open(){List<Screen> list=openScreens.get(a);if(list==null){list=new ArrayList<>();openScreens.put(a,list);}list.add(this);dialog.show();dialog.getWindow().setLayout(-1,-1);if(Build.VERSION.SDK_INT>=33)a.registerReceiver(changes,new IntentFilter(NativeTasks.ACTION),Context.RECEIVER_NOT_EXPORTED);else a.registerReceiver(changes,new IntentFilter(NativeTasks.ACTION));registered=true;load();}
        void safe(Runnable r){main.post(()->{if(!closed&&!a.isDestroyed())r.run();});}
        abstract void load();
        abstract void changed();
    }
    private static final class History extends Screen {
        final EditText search;final LinearLayout rows;final Button more;String query="",cursor="";int generation;boolean busy;
        History(Activity a){super(a,"Task history");search=ui.field("Search requests and answers","");search.setTag("task_search");body.addView(search,0);ui.space(body,12);rows=ui.column();rows.setTag("task_history_rows");body.addView(rows);more=ui.quietButton("Load more",()->fetch(true));more.setTag("task_load_more");body.addView(more);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int x,int count,int after){}public void onTextChanged(CharSequence s,int x,int before,int count){query=s.toString();generation++;main.removeCallbacks(refresh);main.postDelayed(refresh,400);}public void afterTextChanged(Editable e){}});}
        final Runnable refresh=()->fetch(false);
        @Override void changed(){if(query.isEmpty()&&!busy)render(NativeTasks.cachedHistory(a),false);}
        @Override void load(){JSONObject cached=NativeTasks.cachedHistory(a);render(cached,false);fetch(false);}
        void fetch(boolean append){final int request=++generation;final String wanted=query,next=append?cursor:"";busy=true;more.setEnabled(false);AppUi.update(status,"Loading task history...");network.execute(()->{try{NativeTasks.flush(a);JSONObject value=NativeTasks.history(a,wanted,next);safe(()->{if(request!=generation)return;busy=false;render(value,append);AppUi.update(status,"Task history is up to date.");});}catch(Exception error){safe(()->{if(request!=generation)return;busy=false;more.setEnabled(true);AppUi.update(status,"Offline · showing tasks saved on this phone. Pull up this screen again to retry.");});}});}
        void render(JSONObject value,boolean append){if(value==null)value=new JSONObject();JSONArray items=value.optJSONArray("items");if(!append)rows.removeAllViews();cursor=value.isNull("next_cursor")?"":value.optString("next_cursor","");more.setVisibility(cursor.isEmpty()?View.GONE:View.VISIBLE);more.setEnabled(!busy);if(items==null||items.length()==0){if(!append)rows.addView(ui.empty("activity",query.isEmpty()?"No tasks yet":"No matching tasks",query.isEmpty()?"Laptop requests and their answers will appear here.":"Try another word from the request or answer."));return;}for(int n=0;n<items.length();n++){JSONObject item=items.optJSONObject(n);if(item==null)continue;String id=item.optString("id"),kind=item.optString("kind","agent");LinearLayout row=ui.card();row.setTag("task_row:"+id);TextView badge=ui.badge(state(item.optString("state")));row.addView(badge);ui.space(row,10);TextView request=ui.text(item.optString("request","Task"),16,true);request.setMaxLines(3);request.setEllipsize(TextUtils.TruncateAt.END);row.addView(request);String summary=item.optString("summary","");if(!summary.isEmpty()){ui.space(row,7);TextView answer=ui.detail(summary);answer.setMaxLines(3);answer.setEllipsize(TextUtils.TruncateAt.END);row.addView(answer);}long at=timestamp(item.opt("updated"));if(at>0){ui.space(row,10);TextView date=ui.detail(DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(at)));date.setTextSize(11);row.addView(date);}Button open=ui.quietButton("Open task",()->detail(a,kind,id));open.setTag("task_open:"+id);row.addView(open);rows.addView(row);}}
    }
    private static final class Detail extends Screen {
        final String kind,id;final LinearLayout messages,pendingMessages;final EditText instruction;final Button send;final TextView saved;JSONObject detail;boolean busy;
        Detail(Activity a,String kind,String id){super(a,"Task details");this.kind=kind;this.id=id;LinearLayout tools=ui.row();tools.addView(ui.quietButton("Refresh",this::load),new LinearLayout.LayoutParams(0,-2,1));tools.addView(ui.quietButton("All tasks",()->{dialog.dismiss();history(a);}),new LinearLayout.LayoutParams(0,-2,1));body.addView(tools,0);messages=ui.column();messages.setTag("task_messages");body.addView(messages);pendingMessages=ui.column();pendingMessages.setTag("task_pending_messages");body.addView(pendingMessages);LinearLayout composer=ui.card();composer.setTag("task_followup_card");composer.addView(ui.text("Continue this task",17,true));ui.space(composer,6);composer.addView(ui.detail("Your next instruction continues the same laptop session."));ui.space(composer,12);instruction=ui.field("Add your instruction",Cloud.prefs(a).getString("task_draft:"+id,""));instruction.setSingleLine(false);instruction.setMinLines(2);instruction.setMaxLines(6);instruction.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);instruction.setTag("task_followup_input");composer.addView(instruction);saved=ui.detail("");saved.setTag("task_followup_status");ui.space(composer,10);composer.addView(saved);send=ui.button("Send follow-up",true,this::submit);send.setTag("task_followup_send");ui.space(composer,10);composer.addView(send);composer.setVisibility(kind.equals("agent")?View.VISIBLE:View.GONE);body.addView(composer);instruction.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){Cloud.prefs(a).edit().putString("task_draft:"+id,s.toString()).apply();}public void afterTextChanged(Editable e){}});}
        @Override void changed(){pending();if(busy)return;busy=true;network.execute(()->{try{JSONObject value=NativeTasks.detail(a,kind,id);safe(()->{busy=false;render(value);pending();});}catch(Exception error){safe(()->{busy=false;pending();});}});}
        @Override void load(){JSONObject cached=NativeTasks.cachedDetail(a,kind,id);if(cached!=null)render(cached);pending();if(busy)return;busy=true;AppUi.update(status,"Loading task...");network.execute(()->{try{NativeTasks.flush(a);JSONObject value=NativeTasks.detail(a,kind,id);safe(()->{busy=false;render(value);pending();});}catch(Exception error){safe(()->{busy=false;AppUi.update(status,"Offline · showing the saved task. Follow-ups stay on this phone until connected.");pending();});}});}
        void submit(){String text=instruction.getText().toString().trim();if(text.isEmpty())return;try{String followup=NativeTasks.enqueueFollowup(a,id,text);instruction.setText("");Cloud.prefs(a).edit().remove("task_draft:"+id).apply();AppUi.update(saved,"Follow-up saved. Sending when connected...");pending();network.execute(()->{try{NativeTasks.flush(a);safe(this::load);}catch(Exception error){safe(()->{pending();AppUi.update(saved,"Follow-up saved on this phone. It will send when connected.");});}});}catch(Exception error){AppUi.update(saved,"Could not save the instruction. Your text is still here.");}}
        void pending(){try{JSONArray queue=NativeTasks.pending(a);int count=0;pendingMessages.removeAllViews();for(int n=0;n<queue.length();n++){JSONObject entry=queue.getJSONObject(n);if(id.equals(entry.optString("task_id"))){count++;ChatTimeline.bubble(pendingMessages,ui,entry.optString("instruction"),true,timestamp(entry.opt("created")),"request","",null);ChatTimeline.bubble(pendingMessages,ui,"Saved on this phone · sending when connected",false,timestamp(entry.opt("created")),"status","",null);}}if(count>0)AppUi.update(saved,count+" follow-up"+(count==1?"":"s")+" saved on this phone");else if(!saved.getText().toString().isEmpty())AppUi.update(saved,"Follow-up received by the server.");}catch(Exception ignored){}}
        void render(JSONObject value){detail=value;messages.removeAllViews();String taskState=state(value.optString("conversation_state",value.optString("state")));AppUi.update(status,taskState);String original=value.optString("original_request",value.optString("request",""));long created=timestamp(value.opt("created"));ChatTimeline.bubble(messages,ui,original,true,created,"request","",null);String rootAnswer=value.optString("original_summary",value.optString("summary", ""));String rootState=value.optString("original_state",value.optString("state"));ChatTimeline.bubble(messages,ui,rootAnswer.isEmpty()?state(rootState):rootAnswer,false,timestamp(value.opt("original_updated")),rootState.equals("completed")?"answer":"status","",null);JSONArray turns=value.optJSONArray("turns");if(turns!=null&&turns.length()>0){for(int n=0;n<turns.length();n++){JSONObject turn=turns.optJSONObject(n);if(turn==null)continue;String text=turn.optString("instruction");ChatTimeline.bubble(messages,ui,text,true,timestamp(turn.opt("created")),"request","",null);String answer=turn.optString("summary");boolean done=turn.optString("state").equals("completed");ChatTimeline.bubble(messages,ui,answer.isEmpty()?state(turn.optString("state")):answer,false,timestamp(turn.opt("updated")),done?"answer":"status","",null);}}send.setEnabled(kind.equals("agent")&&value.optBoolean("can_followup",true));if(!send.isEnabled())AppUi.update(saved,"This task cannot be continued.");}
    }
}
