package com.personalassistant.companion;

import android.app.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.function.Consumer;

/** Cached recipe browsing and selected ingredients use the same stable offline outbox. */
final class RecipeLibrary {
    static void show(Activity activity,Runnable changed,Consumer<String> importer,Runnable web){
        AppUi ui=new AppUi(activity);LinkedHashMap<String,JSONObject> recipes=new LinkedHashMap<>();
        try{JSONArray cached=Cloud.cached(activity).optJSONArray("recipes");if(cached!=null)for(int i=0;i<cached.length();i++){JSONObject recipe=cached.getJSONObject(i);recipes.put(recipe.optString("id",Integer.toString(i)),recipe);}JSONArray queued=Cloud.queue(activity);for(int i=0;i<queued.length();i++){JSONObject change=queued.getJSONObject(i);if("recipe_save".equals(change.optString("operation"))){JSONObject recipe=new JSONObject(change.getJSONObject("recipe").toString());recipe.put("pending",true);recipes.put(recipe.getString("id"),recipe);}else if("recipe_delete".equals(change.optString("operation")))recipes.remove(change.optString("target"));}}catch(Exception ignored){}
        LinearLayout content=ui.column();content.setPadding(ui.dp(20),ui.dp(8),ui.dp(20),ui.dp(8));
        if(recipes.isEmpty()){content.addView(ui.text("No recipes saved yet",20,true));ui.space(content,9);content.addView(ui.detail("Import recipe text, or share a recipe to Assistant Companion from another app."));}
        else{content.addView(ui.detail("Choose a recipe, then select the ingredients you need. Cached recipes work offline."));ui.space(content,14);for(JSONObject recipe:recipes.values()){Button button=ui.button(recipe.optString("title","Recipe")+(recipe.optBoolean("pending")?" (saved on phone)":""),false,()->ingredients(activity,recipe,changed));button.setTag("recipe_"+recipe.optString("id"));content.addView(button,new LinearLayout.LayoutParams(-1,-2));ui.space(content,7);}}
        ScrollView scroll=new ScrollView(activity);scroll.addView(content);
        new AlertDialog.Builder(activity).setTitle("Recipes").setView(scroll).setPositiveButton("Import text",(d,w)->importText(activity,importer)).setNeutralButton("Open web library",(d,w)->web.run()).setNegativeButton("Close",null).show();
    }
    private static void ingredients(Activity activity,JSONObject recipe,Runnable changed){
        AppUi ui=new AppUi(activity);LinearLayout content=ui.column();content.setPadding(ui.dp(20),ui.dp(8),ui.dp(20),ui.dp(8));content.addView(ui.detail("Uncheck anything you already have."));ui.space(content,12);ArrayList<CheckBox> checks=new ArrayList<>();ArrayList<JSONObject> ingredients=new ArrayList<>();JSONArray rows=recipe.optJSONArray("ingredients");if(rows!=null)for(int i=0;i<rows.length();i++){JSONObject ingredient=rows.optJSONObject(i);if(ingredient==null||ingredient.optString("name").trim().isEmpty())continue;CheckBox check=new CheckBox(activity);check.setChecked(true);check.setText((ingredient.optString("quantity")+" "+ingredient.optString("name")).trim());check.setTextSize(16);check.setTextColor(ui.text);check.setButtonTintList(android.content.res.ColorStateList.valueOf(ui.accent));check.setTag("recipe_ingredient_"+checks.size());check.setMinimumHeight(ui.dp(48));content.addView(check,new LinearLayout.LayoutParams(-1,-2));checks.add(check);ingredients.add(ingredient);}
        String instructions=recipe.optString("instructions","");if(!instructions.isEmpty()){ui.space(content,13);TextView directions=ui.detail(instructions);directions.setTextIsSelectable(true);directions.setVisibility(View.GONE);Button show=ui.button("Show directions",false,()->{});show.setOnClickListener(view->{boolean hidden=directions.getVisibility()==View.GONE;directions.setVisibility(hidden?View.VISIBLE:View.GONE);show.setText(hidden?"Hide directions":"Show directions");});content.addView(show);ui.space(content,8);content.addView(directions);}
        TextView feedback=ui.detail("");content.addView(feedback);ScrollView scroll=new ScrollView(activity);scroll.addView(content);AlertDialog dialog=new AlertDialog.Builder(activity).setTitle(recipe.optString("title","Ingredients")).setView(scroll).setPositiveButton("Add selected to list",null).setNegativeButton("Close",null).create();dialog.setOnShowListener(v->{Button add=dialog.getButton(AlertDialog.BUTTON_POSITIVE);add.setTag("recipe_add_selected");add.setEnabled(!checks.isEmpty());add.setOnClickListener(button->{if(!add.isEnabled())return;add.setEnabled(false);JSONArray selected=new JSONArray();for(int i=0;i<checks.size();i++)if(checks.get(i).isChecked())try{JSONObject ingredient=ingredients.get(i);selected.put(new JSONObject().put("name",ingredient.getString("name")).put("quantity",ingredient.optString("quantity","")));}catch(Exception ignored){}if(selected.length()==0){AppUi.update(feedback,"Select at least one ingredient.");add.setEnabled(true);return;}try{Cloud.enqueue(activity,new JSONObject().put("operation","add").put("items",selected));dialog.dismiss();Toast.makeText(activity,selected.length()+" ingredients saved to your list",Toast.LENGTH_SHORT).show();changed.run();}catch(Exception error){AppUi.update(feedback,"Could not save ingredients on this phone. Try again.");add.setEnabled(true);}});});dialog.show();
    }
    private static void importText(Activity activity,Consumer<String> importer){AppUi ui=new AppUi(activity);LinearLayout content=ui.column();content.setPadding(ui.dp(20),ui.dp(6),ui.dp(20),ui.dp(6));content.addView(ui.detail("Paste ingredients and directions, or recipe JSON. Import needs an internet connection."));ui.space(content,12);EditText text=ui.field("Recipe text","");text.setSingleLine(false);text.setMinLines(5);text.setGravity(Gravity.TOP);text.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);text.setTag("recipe_import_text");content.addView(text);TextView error=ui.detail("");ui.space(content,9);content.addView(error);AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("Import recipe").setView(content).setPositiveButton("Preview import",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(v->{Button button=dialog.getButton(AlertDialog.BUTTON_POSITIVE);button.setTag("recipe_import_submit");button.setOnClickListener(view->{String value=text.getText().toString().trim();if(value.isEmpty()){AppUi.update(error,"Paste a recipe first.");return;}if(!VoiceOutbox.networkReady(activity)){AppUi.update(error,"Connect to the internet to import. Your text stays here.");return;}dialog.dismiss();importer.accept(value);});});dialog.show();}
}
